language: java
sudo: false
branches:
  only:
  - master
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar"
env:
  global:
  - secure: ZiH93eRZPfKm2Dwr5dptxaUtgj5OZ5EO6sZDn4riWyNG1vHplZ3E71Hnacg4Pov+Ocnw86KDEbkXmzMVGYwHJeXst1xrPjUCImEizWCkqXG6bc5eV9vr5KGL8CqauGsGaVxXfrLaxVYF6y7PWk1djUGY+4InCzhDovmF9tAC9GaGnTxFh4PTXyDbc+eSnWfNAuKyTpJ5ztwrjOzTR9lawqUzlJBqce4lkDJkLwVNOyzgcXPaN5O0/+ReDFB2awe8ROudnks7wgsVquM6S85rL4JAIFqgxd/D7+u1AkAFO0VRbSWpooRICRoEa2yr7cS3mYP1n4NsWQRgFpFZI2rJqoJ2bW9+AkaS0OCSU0bmhjMa9WL2iOPnucEnKsLzP/2e+I4ck5xKtXxrUomkRJQAaWkTDw4ZuSNIo/QxIOo0GiiOAfeWgrhsMn9BjmJIo8ajyPjZxQZvTK4uDN/Rqoy49fqJQk6sa3Cy9g2WmHCqQpxt5mHMKbXqyRaWNWrcvYRyagS/W/nJhb1uQmvtKgVtgeP31cFo9dMaFvS7/j9ECNpqNy23w8YRgrIKZzQIzgC7o0H3dLc7sw2LNSR4e8FVrSkeD98+11ZJKWZN379zMscAFXaqcS41GRbE2n0WS/4we0X6kK0zd91nrTMfwh15jsU7XVmd7QAHLOhLAiR8RfY=
  - secure: Nc7F8lhIeIhi1dRauL2gV3o9KwWJL/00PX3irDpboKSaRyWoK7tAEm7jD0uYtUhdEG/p6K5A+6j71SfHB/FcxRXpIgknuV22DSqwFRSeiYeoGdNWYfN3CeArQjeuuuRvOYCS8SxoNapyzuEy9TTRzmS+bFKwoLBdjpCeFJgZtYSnEkOilFd9Dft2uQTrz/0uP9xe5/WED7QxzS+hdBb3rQ/by6ACjDWTG3enBuwJHjUnYWAmJNqk2uF20nUIRICgx6x6YEh+3Zx3a7d/N+LpUMuj09fvxt5d+NlrhCaQYEdspRgEJT1ttClR37b6lwSkGZxIOLR5NuzbaGNeO20pbCgTkVaBjbJ09aTGsCcgY8/eJ1PB4Vcx6PWJrXU7r7fQFeyiinlgP9UD5/eIMAlC2Luw0Sj7eS3N6hRiW/c0mzACqj6FzbFmomAUUCIp9Dg0JSbkx5GaHOVrRvmLoHkvoHAyIi+XCgciBx1NsiZFoXV4+yfj7zsUQzAs7BMKNHICLu+43u+Cc+Np+R3oPuiTbZOEay98NBEOw+MOsKvughKRWTPnIpww8SbZcavwIGk9WOreGWbs/vusR5c1wtkqKynZ5NmVSupX6VIIbACyIXSbCgETtml0VqIax1pgQyLVWhvqp1GZq9SOQ6+390mW6Q8yzc8gBwd+agfj2GIUB70=
  - secure: qU4FS01D0eLx8LrcQ46uNOnxKZG4TDBYqy0xSoShXHinaBWEWVGIOglMjdSLwCZfkFpYAb2keukEq77IkPdGbvxTPxXOHlcRZi3/kvY17GzAS9Gt0ZR0eVOmOwHp5b15tPypCZUosJsAeti3QePOZzkGiNv7WaKmJPIFGRC6AECjV4gFDgNWqSOn6nXzURPYpFpTOQdaTesuTyOLDQU0K/gXnfgbaBQmjTbUMPPUjomJcI9WG/XDDTBs4+gOMC0SvOJpZN0+o2aHi+fod+Xv2aO6FiHSJilBxOxK3vVhRDLkgbTrwotUF6OdYp2j3cqfJIKxxpuIbVfRmALpB0xJ9p7hW+YCp9rJllYrWZ0eia2Pw9jjrFTvZFaGLUjr1ba/wBaO3l8RxviPbjpw8ZeTY+GCeN0G8noZlAXG7v5viCwtSb+MepLUNllr6CapRbg0OWKSk0SQwmEFoJ4T8M83w72WbKGt49rAU3oTVAUS1ibzQr3GsV/OkDD34vLvsrdu5ippF+ymEicvEdr1lF9dcqNC0Tg+Rb+8eaBXwZgAw7PfbXGdfrARytCUSc4c+YUAXrmtRE4ipI2VnOiz+XZo3TTUfS/WhGqcSZQrvIcUWHNMSEy4F/FNgBmXLVfQ6ooqDtkz4V4VlG5b0uXZqEp2QTGIg/bWnkzAZsS/10++lXo=
  - secure: Ebwiu8xwM3HoaOmT3RBfV8j2G8Y6MbJiioP5N8woHRNyYJqZJXJEwSe6wgCaFlR5HWVi2AeuM/D421r6U8G8mKWK5iTkN0re5pWseZjTE+FssmIfy7iksjGjVA9Mc6hj+hTg5xifpkJllDbEiMsNc8NO2WQ+Tdvm1U5rlWebpJUc1GH5mB9enEhKf4nkI4FDbES1wJFxwtg/BczFk0y5XuTdrNabLay2SbUYYoEBq4cd4HbnDmHOnATSbxvbXp3gmKMB/sMJcjWHvlLFqGR4DKvebeteAlFfawjYS2lJ7zP4YGzwxGh+DwZL0Og9xQapCnoMf0jmsfUOa7i0pFYNCJwQqOI7wyIEyaQXoOSnQUEDz+vrdL1ycQEcfuQjOsNQAB3SoxZwPR7aIhukngS1BF2JFlD47vkVP/AzpXrx40E7WTZde4C2kuIg8K6FQxxg5SxD+GAeihXJoTQWzoC30lcgF8+lRVSN7SKzc8rmxSc9YRNoYpwGp0ERAfkbQC1Uldi6itoPnSKX5LGq0+20xhtUSgGXG+MPDjN4KgKqa6tiCDNhJjaera587ZMdnvcghGOwgnlFrZ9XrHruq5OcCQKqeMKWgc5A73MUg6PEj87hMV9SPdj7x/0CrjL38qXdJ0b9M+UcXghsJkXLhUtTGgTJifrbeQmvYbOU3V/Xe20=
  - secure: Ww6xICQMQzB9G+7WzOvO7hY9dNKMWLZETxreYLpLgY7p9NLOSYdvPWAS7u3VIF7KsiXEQZUDa2rJk62yUTfnuBg3jvRj8lrJcsfly+P7cao/rlFsk/UyKO7vAOt8NeXn1xMPn9iwGKOdSDQazl1I5swX2g81diDZqo00ofMzXUiDiLtl8G2moiOq3yeCWdn5Ne9a63qxFrUaevHZ6hShRzfyjXQy+eG6rjISsea2QDZknOy3jezuQtUM72ykybAt5iBc0VRcRvoT8i5eg9qnUwz9HPFDipMSQzQdmJmAcwViaEfI0hM59Xrm0EMKh/IYgPv6RzyoiG0YU2R5BddBejDEN3ZH3OFaaptTmVJDR+dH7IwIPpXXRkJojg7ZyZmKVF/Jo0fk16VYkSbttpJizoQlbYTGAGaUmw6ixuxJemqafcoa6IoqD1gO9gA68fwFul4+x8Mr/iR1X41ORpolUMH7veuAHHvZpV+lJDVMdhW9u2kv0HJhEFc3OGlXm4GoISg7pHhruiVu/L3m0K/S3gqjUp4UIiy4Tx+uzxpSoawm0/5FbujZ2SWVDzH0ZTeCkrwhtHHoObNQPbnHH2M9se8EW1WT1U7UkQmk9w/JC7sCxGZxsCfENHIqIrnSIIKKXk2z9u4EG4zyJX23gM9wQ9UdQzd8K2g6Gy4o2F8+J2w=
addons:
  ssh_known_hosts:
  - github.com
install:
- mvn dependency:go-offline test clean --update-snapshots --fail-never -DskipTests=true
script:
- mvn deploy site --settings=.travis/mvn-settings.xml -Ddependency.locations.enabled=false
deploy:
- provider: script
  skip_cleanup: true
  script:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${SONAR_ORGANIZATION}
    -Dsonar.login=${SONAR_TOKEN}
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
- provider: pages
  skip_cleanup: true
  github_token: "${GITHUB_TOKEN}"
  local_dir: target/site/
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
