language: java
sudo: false
branches:
  only:
  - master
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar"
env:
  global:
  - secure: LGe2u3guKD08Tu8/ujj8ExlTV2PvwhscdVzc3G+elrtgeocvbtXQRoJDX/uJNNZAgt+HTwMpFxnAHR6TOIpzOe8fRWF8/SUhvZ3uohSN6BwKesjM+J/9RHTRFMXNx/qmOY7kbhc1bnB8i4kZQa2YibgsI9x7JX/TOgWeIRlkXhIBoOpwuYX20sTuJOrl9UsV/wHQ6BsFhI0gavtW6nqYaZUo4A2ChTY153urPqShOrxPzafgaOVf8FRtq3NxnYQj7d3cWq2BkGZe64EzckQNE+hs7o7zuUsZYmXOEGn0KldUh/LsfCPd+BdiqW+NboRX2zuGkVZyB4Dnxn74wR5EcLVVZXDC+93Txi7BITuq8eoTZLlayL1Oup3nBuoG2bUqYzJLy1laqZPLOWMjFpYwc8pwT5xFKOcp0a5OTIfwCDg0f3Zi8aAywy0rIB+K6//skZ3Ihb4G92edAyOsIADWXfzD/db35U6rD5V7zY4iCDsB5laUv44LAokBV8Lj93zoTe6nCvv6e5D9Ees2ucGhsVjyYlQpEz479K9ARQd86iXLnAEgzKvIh7tJhwbG40g6wDiEFR5mq5GFooPMdjgWWBsr3Z5R3dbtgqCEsQECR4Lerq+ytqt0uUWONQsZn6QjeU4Q+44Ww+LVOwQO9D3w61huV3NLAL7K9tFbew+CzTw=
  - secure: subqTHgMGJfzumm70UcpkTbO16v2PFimU+NHeOfoH3xYCA1lytp30eqcGtKvxAyzhVQqrxHOWzCyKSOAw5IWoGMvSL/Qwl96uyNN6BcOv4TOCfAjKGzssEN8aW7GJ+3Hh2SRrl/yujxfG4pMNLR5i+0NFori8mZvznJIJc6H5NM4lzGuIF7nRPtnR42VV2YqrzDZH8BHvAFsMLcMUWXS3rU4eedcRjZH4JF+2iEgyqCBg8P4DJbX8spn5sejZPrMTj2prrSMzmT/SWvBpOdlXXg7LHex6h/PHr5Dw6UysRfsB2KlbPq0X1fbEYqJKOdMIqnilqpoGQh50o7luLgJX6pzzFeWuknxUwUMr0IyP3vzhn9+46AiOnim+Sw1LJeE6Hm0nXkYpm1NH8Ge1m8snJDeKO7CkRcx+uK8TE6LqthgxxY0oSpLVQ5MVpncAqUhAEGZcLmpqsE9tv43zxzJE5H9gDr5/3SoFICw6VH4hWEmy5EuICZ3BXDdou2Zz4oiExDuJ+PTc5DjoW5zxwirrM2ISpccJbYXFsqyLFDAkrfrigYxv3wTac6EynA0hy0J9uZHz1Jy3AeBx3corBlYtsaBD8oxADneYMTdx4oRyYBGz07mU1Wz7JQIJTPsoYCrFHRDRI21Qzt3kixS/CUXGKUhs6Q02GQE1IBdNP7UM5Q=
  - secure: F/VDouZjOO+Wr8MnSQ9iddD2q6ZGePr9Wq/6xzdK9AKO7AJJ+n5c5oxYIEktjrBACXUBAK48uRoYD7v3oeinowI2T5uHl9GndFR5PQ72HXgbD3xG/06+/a2+/sxcC8AWes76cRH3Iv8N2c797ehTT8MTL/2ZvdV3QWf9ZfnZfbNKv6VU9UYaCAOJcIiaUdQZneDFFGG8gGd+D7HuAL55W39aqH2fZg7cR7NO0AqagIVJr+W1enf/jff/cFmIe5Q6F0aBzGpX5GjZeIvcAfExnTxyFcJ7o8AwFo20MPaGp5E277PkK0+cXvIAeuINwAT4+QUJdp5CAEMRK3EmXgfBfInwCW8pTLKwbx8/C87dXsc6sBAvhmKnHLrE99qVslg1t33X9RifUbU+5Ny27dgGiXSMljlEJgsaaVhlb3VaTeWN6+hDC68rlId1cxf7wzvIEguScspC/ZOIXabnwToF280MKTlshISriidGGOlg1ZlBaCOJIl5bD9HSPODoU4R5cUaSgy631W7/KbPU/ZimVyAnBF9FnNTGFis3LH97yAGdnX9yFjEF4yGrrJXMmojXgHSV+ZwixiW22/yeoJoyuRlimD9cZgFghYxJC8efBTF6rq1q6IuP2jJkDCLt9heoKbj7z4vhegiM6Vo1GVGvkItO96IFLXHDijWp4aQlpvs=
  - secure: QKglYLx8MN9H0LLKX5YVgWsz46gXFfX22HwfsbRO7SZpttgcIkPE0Og0uFde+4tpLzqp2AIjKNgNvodr1aasX9dFZxjyqhzRdRNI9N+BRQgyrtLe1CTvsqbVgegbJso4fnBob5w3IwDyzyIADXjNKSsN8zRnVKuuqP1DQJwLsfyaQF4UD+g8zqWxcpfnALn85XgvL3qxiguaMWliTa4B2hgwBoyyNHqBHXY6OFvHVUyfvg6rNS4QPmgv8TnNlssxZ6FjDEW10Q48H0aApPYbWBWmUmj0rMvZjxbV6KmlvsZfrcs/wWrQ6N6BRIWcTkdSU2iDvTvxeuv4j5u4KPY4zeneFA/yb6pnuVxglgbJgojbH9mUsstTVlufhPG3mic4RQRViBviMSS+lnNztDKpjnx7SzmjSHULGc/N7syPG83LDDilXEQlv3PTNxeD73ReNAsMwMr5tlESUdQzON9Hx6a4cSs1kWNUvByw5IWqf6OcbEbgbeyByXkgjJajadxfAJ3wc02V+luBPZi0VwbFp6kcTt3+FsuO+ZzuTsSA+9esypFUVHm32vYOlLFpcCGrfKc5Jbbcybq6EU16Dr8k2TWPOiWoIsfMDtr9wCLy6nibP2ilqg99QZgrbeB3LZJQ74zbkQyfHnLuytTjLJv9c3IKY++YOKqR5hkQZ0JvS0U=
  - secure: miSwSR4Q9ZuaXq1IngCPup1b5S54A1rx6XgDnxZDgXxrAHz03qn77vqZ2lfiHpyTWEo5alt1kJ3LvjVwxAQSgnbqgYu1q9nXO6sqbPFGLY8/iKekMOtO0zYI1A6N52myYRX24fEp8pniVUK3GXbtTF4b3V0W6HHo//W7cwPU0Jd7Z4A4OoZM1f8pTVTp1ES6R9duDE+pRRnjzarVqBODzAx5Go/wkFvr5mz0q9FFdN+55xS61RoZbve0AuzmCEj75dVTGjkDQaHsEMw5xPfja3W+2q9QbvEeb6wPMgMBpzgEZaCpi/C+cwz/UzRD35CSP9OLWZm5rRqCQIgJi8grpm0h+Y7NAaRSHagVtz6lWWgSjIVJFwDJQHpFzG+ji80goxFI1mD+TEZAt5/d0dyXlMYE2cRjSBg5JTLnaHr+X/NXzKiK5U7cxcaA9uyrJxN0EZypFTaQIpHc3YFlBppHIv9N6CeGcQkk9gq7AVV7Mtrib0rAcpMQzWm/3AAbhmuMPZlOKvNS1etcUzhBhGM0b+INWXni0PuGkcU1KlguqZRlEuaTGQO5XMztZOQ3LMacAMqp6/BSalOAY79lBRPP03t78jDiDG+YmNNAHs/H4mBi/vMjP4rIt3DL01xmVsR50ufF6SJTKgxFG2tMPsSL7ZRfhY98L8+rxPfkU65pBNE=
addons:
  ssh_known_hosts:
  - github.com
install:
- mvn dependency:go-offline test clean --update-snapshots --fail-never -DskipTests=true
script:
- mvn deploy site --settings=.travis/mvn-settings.xml -Ddependency.locations.enabled=false
deploy:
- provider: script
  skip_cleanup: true
  script:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${SONAR_ORGANIZATION}
    -Dsonar.login=${SONAR_TOKEN}
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
- provider: pages
  skip_cleanup: true
  github_token: "${GITHUB_TOKEN}"
  local_dir: target/site/
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
