language: java
sudo: false
branches:
  only:
  - master
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar"
env:
  global:
  - secure: b/6VEHmfosYsXvO148aOi8Buuk4iL7QFB7T2/6fxYRTULsLmsY9OVnyL6wvyxuMhlsUt+wPOZDdd2TVXs8MEwAn6mwjIRlClh6UncU3t8V0lj5bIFJ6fRGm0fo3y/vARJx9IsvwD+0q+/dEAjhLdxSMHGVIos6K2KiDM2VTgVOlQjjwv3y6PXpb4PfJ1ZU3I897Ee338e1o+4BDiGnkpJu83X3VxX7a/n6PqvDUA/peyqROU6Fofd3Rzml+qwDdrsL+z6aURzzqoC7x123jVL7AOvXyFyxgs3QQZkZU7GEfz0t999e0tSLsnhzqf7gvfQsHHtY16vsEMXP13hfQqdTk1ogvr7c0I7BjENQNJv6qvYIgz6VNfaKE6R/Recs4zOpcNqO+RIoJ7siSn2rk+j3mi2S2REwfEqQ30oBHgZlSBFz037EfSlEVfBhGu+N+lMLC0xEb3AsAHHA2WC2zrjn31vJBYL8llxdWBGKLz4euMhsv1oUlL1oQjoiYl2T83iCI1PFNTw6aw2zzsL3+JQ25bPHuiHAeA9oK4aMSwevt3gHzKGiB/cIJCnDTgjtLUjhg6M6PdydKYGJkTKvxTUO1MeDTdJzyvyIQYGcaqG3zDYRHJRdNya4yiEFDKkM12PU/4bhv+3jFQKfQwj9qxoeO1/0qtQrEdZwIGPVK/LIw=
  - secure: sDaj+GH6iysTHur6p/7ePZrvnvAhomJOZlTmp/PgnNubLpXZWIqMmQuWjTY8r1S+EddRszqUTsd+eMwOPOfkfZl69TcXd/N7AmOh2X+K4HaRWVUAIq/VhfhqifIUG7Y2Ze0UK0nOPdlC4JhLj2jwZZiMgrITdjuEHoHbJPzObkoZdkycBNNE4zJU1geTukBW3Bm7vWUiyrW6+EFpBtCo0X10cgKNsQIZvoIaJeLc6YJEQR+e0hEeYED+qX6c5OxlFgKBqYAjO0lFwAaMB0NRIWuJ3H2nb3RrhIS/aHBz1oFFxhSZtRr2iWqSF1WdL+GO4aR9VPLoGBTt3ZpEawzt3vLygnSCbT7Mdb3gNkHrCrf22/kRr80Lc9X+gTaF1QYij+NiCx+TmR9jurZ3eUOZt2SVuYkvVEAVyqIsWzK6dy1I+aBa4Bibc8PGqUb+yrz9OngA5sTEe7xCoTjxwSf9UQ/PiLPjQfwh2+ztTajKj0n5DkCSjlbJpWjjt06OGHomQSd9It3GYeUzhar/6j8SJbWMEQBSsCB0dzggxEEISIJy6VivSQ9AJzAbP0zuQ1Pjf+mPtZUTaMw/SRV1Eu6TcVK+hS1p7AWVIr/khJuXMWixBkknDHUcOQIWVomtPXDaLNbaShXZZO53qyb1ZuZgC2WzfI9FuOpesLtzFbnT9cY=
  - secure: tlcmVUN+UYyBFHq32L6x+KhgHQUNqiuXRvM1da05nGC3ZF5GhTkTGn7nrE2jWL6tV2KqqRrWA9BJhkzMoh0EuiDLa/k7ZyluCkMplSJyfBWadfJSNc2AhP5dFeHIJMALjwEh0AG22I1n7lcEDNeZE3AS2GCda++oxbUPVWdwBpDdx7Dbxi8chn48kZ2xQr524ZbZudV2edc31cDS9mIFG3wCo9xImcAJLFfiyUyeHtry2uxCkVpPjXw3WtCL0UFaRlBqmcGVmk3wbMf4ZIkUE1/6qOJ23gJkQ0nTLz3MxQjVMKxV/LbEl7Mw3PnQ4UnD01Qi9WHOo/2aRw8xI+JQi2EF4tm0YHNYHv1e8AXwDBXRqxpH559TAsRNgTQVCNarzDrtLvqND9hePFymT0ZMNAwUanfh3ze2KULhBDYzO0+wwY2EfoBNmnqAuNdi57VpCdJYTbwf86NLwV5b2lfZXR0ncX1lrFlp11hVrgvgyu6Kq3ZMxAL48HPE92Sl0gDKY0r2E4i2uOV8AbL6lptCFKzio463ROUm1sN8u8zR2q/nlDL0302588zHNqsLV4kks47LqXG6vNiyCBjAF/oP+Ar8IZr4vFfWUY0n2lAYISjrWfxoE6URrbRZvki/htPLSoZYAK+64G16gA2ZhtZU1GqY5/mREACUDYWqEZqchok=
  - secure: jUFEALlxqKbj9s/alGxZc5r1NSIXLCLHTZLF6p9jdP21yoz9YdHSXhv1mXl9s5y/skkwVik3iJwFAGfPGcaCvu+jiSBJss9xDgp1RuELaa2RmAf/etocnkDy32+jPbMMPJ4caSvCoaqHt+xbefq6YdecW0XZMh2Tiq9jO/YvQWg39+ll6YgZVqrtKDsAyGtH+Y0mbMf2Etd/cmJLdklznDRnYQO2bUSBcVKFuy6mnSHWZLUAMbD1y58NPe/WcGSiCyRK1bmKsjQfsvGtXqJPFOu+iQhO5BG5Gv8NwLMJjN9vsUJRKHH3YnrTxxv+EGgtjQ7ItBwZJvsX8JJaP4doG39lOexXFnTQH9bfMdFHSV4oNdetnfl1ZJWqjn/eYEFBlrhIsCubW+DI8L2FVBzR6s5hoH+KcCvR7cQ2cF+TOTGZvRjpiU8e5dV7/44Jmwwo37uJwG6cVkKq9DgOFU2KX9Wmkk6la2YIQ1llwRtK/XzfjmFGaGpKDgh7yDTNEOxR8277Ru9kGg0CymWDoINRUqd2Hv2ZFL2YuHaXG8/vJX854dIo2OyWhXJSftM5rfY8O17iy2mGPUuDrXv2DuwQghhf+aJJA+EU7gx311aDjmdGDtY89mSyswiP/eZYJ5PWE+d8vk6eO269y5aGRHvs4OfE5zw1To842B0AeeBS774=
  - secure: f1p3d1POnO3hVa09A7ZVNkq/67W2Sq5ZRLYFE13kAubqVMw3HUgj94CSlsGw7JxPvmIzBnR1DfMbtGO5dHw90EcFbIm3wzo7DiU7tYK++JGxO4LmnkxOYv35tzIjCxxYzgWUlTfUacVGlLCP/HQh8cMu8xpXwFzlCYCXhqTaZGWwQn2NUU6YVsZNJKFOXimlvz1/VBniSlceleXj9E1OuwYGtV0xXDxOM648XwOCQKBD2slkoeXNdclutLYtpl9G9mE5lP24iPOqSwir/9GB35vhUrGFMLkBAfA27Jx+L2DpAxRAtrLwqESfBohSloC5hTe77dZ6Kvr2tVPxWAlJRcXSliAlGx85gQr6xwAZbbITMX8a9wVmumlN9hPcXV2fpIRUQ00RHk8uYJgrhTe2wCrcuZs+gMakjW2P/nzArYECkyxDsJiICORvxOkXzwRyzlbP8eA/lZFM6TfMCwwt5y6/zFnliLqYh/RKuQoBZjwJ4Hskom5L34v707+YBSGJpGd1W4Rs9XtdeAc/V87+rSYYuyVxoBul9ttNSQ4Atzh/1XOgQzAEPO4SXAoF4ugqYeYCLEnzN2evK6c9dB7f+1yJ7WGdCAM3Go5awsJJXxYHcwdhi9EJqXMe7H3P2OZZvOd/L8DNIabR1YO53Kaih3ZbpOQtcKsBydrdBQtRknU=
addons:
  ssh_known_hosts:
  - github.com
install:
- mvn dependency:go-offline test clean --update-snapshots --fail-never -DskipTests=true
script:
- mvn deploy site --settings=.travis/mvn-settings.xml -Ddependency.locations.enabled=false
deploy:
- provider: script
  skip_cleanup: true
  script:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${SONAR_ORGANIZATION}
    -Dsonar.login=${SONAR_TOKEN}
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
- provider: pages
  skip_cleanup: true
  github_token: "${GITHUB_TOKEN}"
  local_dir: target/site/
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
