language: java
sudo: false
branches:
  only:
  - master
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar"
env:
  global:
  - secure: k8sOh6E1K8ngdfgYiL3gUhn5mdywrtxjtsF/6j/ZMcNlk9wHDXdnuJ90F2/6T4Sl52dmEqlv82bDGIctonvJKi+ZBhnGHqHEfXx5kPQZAX9Qm+tsZjuYMMbsoma9wQqDreJDcSr3TQhSdvt2OYNl8cv0IYu1/oSmcuyYd2V+O/cMlfphauwbte0t3+2WSDG00AEkhtiRe5xgvjV8ra59OXn70eav+u1g08HNzt6Smkb8Fpaz9gCnB8sDWOQ/SlgpK3te51C9oZBAg2DI786HqnieOC7UYxdjN1m/mT8wlUlge+GVYT5i5aDlJOmqV99GcSgStrFKuuERW2FH0wqOBqCFCFjCIlkFrXBbJd6ARrT6AwEyJkvDtRoET7CZfRYYR/b7LEVDbQwhDePJb9j5EiGaiBZyYhVzVD259zadUuhiVTLED0Y1gjFA7SAZxAPsB1o/EsZu5f8L4eYlJzdgNurMGWXh9ULlMqwClAjQlFSwxMeDxeIbKuYRUCwAI6mFv4cVbqr17noCf2PV7/LSkwET6j/kj8RGwjmaG2E8ACusmLvfNDClLokjUvhfbWEaVLKiZHIy87TDAFTpLT5YaNnTdKDgWR1ELuj3qn/QWIFnvHjoQHwqDZdVgvwxRkI7l3Un6IdnGbdjgBj2ZSEcdctQDLOehAR4SgpOIFfUEE4=
  - secure: kLyK+GXS+kUd9c17AKxE6AK0M5yWguoXtndcZUzlwJ/BLxDaDroxlpxM0OLbnTs9AcfR2L1W7kA4VGJVFLuLTuiVeM8SNAF13hDlENNY+lUJ3CzN2mDFNUSO6G2kGlWQFDMcA8if+Z+Olnczn3Ivhsb2P/tL2Sg+Z2OOOlW7pG4BI1BfcSuk+axUDZRYciAVLC0Bj0zW7UnEzHWXHBqr0f6qRPv8459AG4mGE8oOkAxS1/RTmwCF7BOyUf4qgLKOmBa5xNW9dWKme1r3nuPqJr4LjKDXLILoFs5PC+dis1FUTe4YZzaYNWzM+GfTfueE5VB+vcHL/IadZzh1qT5ycVcNh0o34ykHBRVXSKI2F1nhV1McYU8XR98zluE33GgHSQ+lkbFuQeR/yd1F7yC5BMO0H0PuzGKLQd2SIJT5oFBVp8Ri3YfDS/LkWu3p/aEv93zRUwOuxmhRt6ZVbzE5vtk0cVRrQqnCRyYqB+dH7Ux4YSH+UFrI6+wR97oHI1TQgWXhVUyjAz9M4D8erfyRtRzbGUDaDJeGAtGCzM6xkYxpAe+PgV75Y0jFnioM8MuMR7kvira+BLrRN9YEvWW+n+OFPs39BB0I6DCwfHTXABktQwDhG9uqt0DZiLIhhK1MDOgrNYpuSPRy7ewEbANHRf7d1x9eMhN37dkAtPjizW8=
  - secure: qBEJ5lUCLNjnkxJbnzWW42LZaL3SBn+4iANSr14i2s/3O3mA7/kcAJCMlaPkFeT87SOCO8b6coXyQh7pcenumlPXTt8Ek2FCox99013g8jS7M+b0qEnX9Io61TtSzBktxwA6TsRrivcI/jhpZzvshOrdXpuWKemdEAQJfu/FmOR4+KosMokHhRQ9k2Y1Ni/uOjV3c94FkhuAP4QSmvNAxKe9p/JlV525PbUEF5m66BCwpkA3kQMVgGU4p9OV9L881YQ5k3UlfGkuauBJsw+WfPIEuuMtSgmFFVocM5G0VBeo69aJcYu1edwkLroShR2MXUeqZKZSW0FaJwLH1hNijaN6QwRVzxDYP5EGhZkSKUliy6Z03AOjPHePXzH/oU+BkkctOXqZOjJBbSTJAx1K15qSTsLLo7M8Aa7lWrK2nWrxW3EQ3/jWEvjH1QL8Zx9WQhmstyOMqfoaM2J+jRYv5xbOea43H9uQ0+n6nGfvV8Gl4ZFur1cpzE8ZwmxR7Jyh4556aV7VCFu066J7UqMRctlceGqdr4s/z9IR2OHw/ShhgsAA2J8aVjQCmgw5xoMHES4AcqSCSsSVUVtqPrvmbdc9S/HHvPGO2gzorzK73BKGeiGbeoRJEhCQf5J5gTsuqrzbfT4aqamTz5dGOuCUfxz2p390EXwitLKCwuzzvsA=
  - secure: g+WFxlw/rnRDDJU24qrmaxDPtM29ybtx1JAB8nt3Whvxfpxx2ykNBe65QFGcAUML1HBRgmnEkIicbEVaTLc8LxDaUalcjWvrooprMuNrVuXQ8wy3ougazgEBRBM8olYA7U9M8Fz9n7y5ZhBeiXyQQI3YQ3R5tOs5EqhTtywYLC29B8ZZmfLQnuyIPOZmut55hDUjjk0NVfaRBFE3qQyQ3p7OgJgSmeuUmkVsitK0+eMoWSbeJ5qwsUXZBnh/Tq6AY424uR/XHw12wdGnLIZ4z1ufuyDNYVc6IoMSpXez+X/qWPg34+JE+14CaijJaV7mZ/mUVriY1imOPp+cgj8aBQXvkd24AOnMxC5t+LUQcrVWhTHgNQLQYovO+WAX7kcnj1BXioVhRXfkDcjofSXjz43U74LuWdfdj2zaE32mizEqE81GYrNs0+diZWDQCSTZCbsoHIIooPm4UJyrIzLEn/yr228qX/vJ6i8MGxscN1PECht83mS12BadAsobx6ufECyRuy11ZUnX4ewM4jtNEVR4HzXYROCfmNAs38BZF5ItkD9G2YmRFuu26EVN0t0FLY6hg6tQuXISbhKEETomoiOzHbR0/xA77p75xf/ZEoFbu5BHDRKOcIIzpVPZqBZCGWakH9BXpVjPwdWAgkdAY3H80n6/g5ok4jQw4AKovi8=
  - secure: m3gw+8aXghpkhoav1EKdptdqMm+Ix767+7lR+/1rbLb2EHz39DFqdHLASUWkvpB6LcikiLQAHar5xlIeUwhxdLdQQlzxUTL2vpD4Csrqth76FG7a+8crEYKjYmLq4oraKQxfeAA7Gm2Picot1D6muzGhqXeF6Tw75SmATAFgyBjFy+/7aWKqigzxGZYqCwCCV7FKgChvbLBqfqE53yozjjUXiKn8MIDb2Pews0ZU4zhyEkERkt3JehcZuT69oyC9Gfe3/vCPXgeDXq2sc3plU0OJQkq3br+XOG9EX+nT0jBlWN2A49zSprT14B422CQPrhuaLtdQ8bPag9jbnanWONSQFF0xl8C7cprVuT12ap+E5i0pmd2qzOjZWlKHJzz1hz9f3BVo2uQhEv8phqCFT7k1SIHX1Hhj+khGVzr9IZnJurcIYtZzJ1quUuQIPXiAZ/TlRBGENOyS7QmIBPeXvq4f559GGcF14a8LzRZMAYRGOR24sHFzJevK0bAaFHWMOzMGwmKQb9U/I9pZ+G4Ec5cNB+XxiCuqNMNVPtT69Z91K20Re/+0sIgaqr3BwKeEMuq9JITOizDJ5AvzqCXeENOS+spgGcCP23CYz7SvFXvaFUTB/wcx6SA3hCSDXVG8e+5wg98/9Gv5YGgfqUnIw+VezHVbPzp7AOzyClfmRm4=
addons:
  ssh_known_hosts:
  - github.com
install:
- mvn dependency:go-offline test clean --update-snapshots --fail-never -DskipTests=true
script:
- mvn deploy site --settings=.travis/mvn-settings.xml -Ddependency.locations.enabled=false
- echo "***************************************"
- echo BINTRAY_USER ${BINTRAY_USER}
- echo SONAR_ORGANIZATION ${SONAR_ORGANIZATION}
- echo "***************************************"
deploy:
- provider: script
  skip_cleanup: true
  script:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${SONAR_ORGANIZATION}
    -Dsonar.login=${SONAR_TOKEN}
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = false
- provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  local_dir: target/site/
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = false
