language: java
sudo: false
branches:
  only:
  - master
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar"
env:
  global:
  - secure: uGLbYejX4cNe492R511rPUNkqCs5zUjB4XyWwea+Bk2tvcgasUpi+3joQmW5V7HRv0RskDd++JQQe/c91piAi6O30REXY/5HpziaATvSQNLmkXqE/n21wlNbLlFAD/CltZNqpFi8AqEb81HfGjWCO5+DEIV5rdpKbqX00Y6mz/FMu/097KgePIs/N6d1sZaY4yhMQ+Zd9utYfko8F5KxGsIOLNcXQalIXnw6iMbog/rSdM7/dT0ELGeqJfgEwgfaOl+QHpKFTJrn8W11Ca0M7QGOxnjbu8/YnzmCpMn5K9G4cEaB+DUJhTT81P1r26NaEkDnf9DKag4xe5qrYAu55FNqVAbSelnFxf9YshjnZ7OTK7wTjqkoGa+BiNQH5cvYr/HD21M2HO/5tV9DTZIgpM+BRRf/NvmDysFrw/0c/FCO7nHip2F3pXYTSsQZvVvFIbvWkum9ScSOc1bGaJPdnNT3jq857DH3TARK1BY45OirVnk0Tk7nZJz23b22fX0LUp/7VKVJTqRyRIfU10Ii0tMlQWEl5jDjNChwLGdH2tXWk1xHqva+QvlslZLBH8Nr62y9mFY0ten1Jbkq9jGnZzzjqDMpjbZUuSTLl7GZvymR2P2ZETd8yR5ZmhNom8Y5pe0n6k2MqNj6qJFxSAq744lNgQ1jm5oBpgcsDoY5Mpo=
  - secure: UPFcoXc37f+IBmeOSFDpxYSpOlzGmrqLJ6k/Y0TUqD66+pR3kVR25FIMND76yj2XR/EoJOjCTFuTnFTSl6b1r7D3mvlj8B7FMHPeDVfK/SQ7J/bd8YLDzlrh9m17ujF3M5iRUOABolL4a+AbEPicnMakQJiDUdKdjhKPrOMTIajmZ7i6wgBbG17QQX+AekpWU//Pw+YSFHiXAghGxxhGkfZwJZucf1A46v45E3mqj8kze7B1POIp4XF9178u4ZthYwrxbJTzvwURKleB9wdWHC/L5s4p2ShsCsrJgZkYaiBKWmnpxlwetkDJ+Po9D/1UO0ZYNUnxmCXqNpTWIgZcH92IGjC+/TDtrzzc3qQmi4bOEYr21B+Al+yFPCGzK7IPKbMHD3chpke3230KGMqkXu4nFsgUjJlSlEkdQxDbcbBCQOdMdWU0aJSBEXSKclT8X8LL5F6pybppF3dHM1quLNB1WoJ8JXFNx3QmTPWWU6KOA7oGLuuMQB3ioeRpcm+zmiBX7lJyDDT26cKvCBt2no7G+qB9GZxrAfjvHwVw/pPu1K+b7qywducFIEqavrd3OnhfSoc7MxVZdap1y70DQ3wJ2BdM8/0eJmfgJxlAKDHE9M/yy2nOyttNZEhCymI+rNFDDeYFDbt1y88ZrzTBe0tn6CEo3bciSoAcBqPlU7A=
  - secure: WcM84sCk/p2H7dwfGTQZeusdvnUCAn8cpEZFWmTQSdSovrYIck4CxCGq/HhbHL1wmBUTbgsKPbQNxPMkZs50AFSHIgiyIsNyuZdjsPTvAa3Ttay6r1UQZxFUfAjZNcqeiCSafTuKfHWB2JwEjU/9n/UYelGelNZZrYS6rr6XgMBKs5MIM/10iiypF9DYeLq0H7cqOP4rnQySrZpESLgg4eK6KyZvpp+D2Mb5IKEt2m+CAzhK993uxQO/p8fttXpPRLpJk+l+Yc48z7hmzizsUfwVV4RFX+7fuAqPMxkE2ZBG88Ve+Mfpjt2G78N9kAdwctGahukAQXKgx6aqdl3WUFmJU19HUogjzZJp3Ax9rlm3z0+8RYY5c9FaCc7DWOWm8w56BPlXVE6HvtswhXbQTwVogQk1Y6zqajWaJhbGENFZEPR18SwZbRlPaeso3x5jwRUBip30VkgA5HQmWL8IXY7OAZY5EtMvSwZOHCe+3D6UH5EJ7vjSVetOoEjb3WMT/gWWOuEUWhzSZJgmLCcdEdPfm78diu5uy3MaT13ETdPxe0Rwuh/FBw1lXnRuBvyvEhUqjXakUZrg9sRKG+qXoYSL+6LQlGpYEexaBHbTKkiFmjTzAYQf4Zyxmfj0OzNYOk0S9NgX6DtPm+B5np5mysD0RPcN1IPIYFFkDlD2JF8=
  - secure: RE9jhd3GdV085owadKwXGiB1axIeDWNsAQK1a7pGPbrItFhZ4OxoAW4slVj+7UAgrBo8/rOEpXtHKdvw3KuDBNd0IqEBMeLTdP2C05xGT0DO+yDJlpQBj4UAz8LVTv8/SdE0R+QuV3ZbllvTrjb9k/aEEnM3C/zEZ/l2NvqYOiaTlLvm8irKCigVvcHDViLbK5j0GHfo6t/iFQEQm5UGgLBXCCg1eYN3E5hGlj8iW0lZCwWyCKhG1jhOIEQn8fNIZfsxZkEeS2D3h1JYDdFTZmVU8vn/QvwjlYanDSWz9oMrYpUd/h592SBWKiLFMyKKiUIyV6O/lpOYu81mxBG11mcDg/6ulsS1bD2camrtDc3pViDhIWw26uPvxXwzDlki9tg4mzWCyLut6/G2Alw5Qq05U2S25PWcbuK4p90X/J60g9gbhn0w9tV7mBbXVW9CBWKszwiF15eetACOivWn1qAEVV8/jknBFvFIpl8/hXidtST/vqsQRdqoJBNYPoFPrYp1hzjQkZaJBoV6oPj/g7+6aC/8n6JwpOmWpuVMteHQRB41HsNcDo+XJFaxSvX2xc35QyQGA7AqcVNLZs18kqjSeMPi8AVBYfFimMyeJp9I0o7YImEDEOwXX/CV8hRoCuu72azLedb7R5+M9K4TSXbaIteihl9hZPpCGgMpb5Y=
  - secure: AZdNbfBYFfzFMz7BnfLUz0c8K9nqzvQcQMjeA47sfCR6gL2DT9BpZ1NO3j0Upo60jzUjl8fBAnEv3O2UNNVb6h5MZ/i1SIx6DQB71xOVTJeFMQBVlPFeULJ5w1uiP5E5Y1+6c8TeYKo651OrTvferLX5vMZl/f9+zqd0biNBhuXQoIXGU8URSXDYibV6i6LfDE1BFQi3JKJJj6X6ZQVR8McBr1hhI7RP3I+sIBvdBBpFniNayJ7zD9Kpg2sjitUbr/dPflwYFzrnOboJqsEI7ItO9JmsjJnD8mu0qtI9E2/UT7Ll2ijkj3/dRhmfJvOk/pd3ewiCfBA4TvsZycC69mDDaED+Xnmr6XAjma9etxZRXGN5Fer4llfOMvaqQx6cxh888kTTQQuOtkIn/FvRNmUTPywqV/P1xOPGNVX4qnSg3C+T8xrWTC7GfG68mbnTpc1KBWotlOl+/k4OjPuqFHMoKmjAiaH2UjPFGo3TqXj5TtyxGi5goPDRQ3jIwa7uTRMlLhA7Wb5TsLVbmazW3+a4nnmJTbS0AMANET9atXJqo4rlaQVj0ia5KhkFXcVpwWPPeUTej2S+n2d3NEewM+5golYUOEBYvWujUU3ghEdfjL8lSETP9T2yvdSqtbthb3ugk5xr/UF3mHDIJtpQZ0C5uKzVfhj+TOXP/1dIT2g=
addons:
  ssh_known_hosts:
  - github.com
install:
- mvn dependency:go-offline test clean --update-snapshots --fail-never -DskipTests=true
script:
- mvn deploy site --settings=.travis/mvn-settings.xml -Ddependency.locations.enabled=false
deploy:
- provider: script
  skip_cleanup: true
  script:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${SONAR_ORGANIZATION}
    -Dsonar.login=${SONAR_TOKEN}
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
- provider: pages
  skip_cleanup: true
  github_token: "${GITHUB_TOKEN}"
  local_dir: target/site/
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
