language: java
sudo: false
branches:
  only:
  - master
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar"
env:
  global:
  - secure: jxDJLf2eL41Qpn8bzkPZI8VpWEaXjFyXIE6NnXLsmyQhk55pxnb2pSfIqxYHGfNCJ+V0ohDXQMpovIz8q9YdWOWXky0gczX3r4CzEemCDh//it2cwb5yjn9grbiAWjSZdegoJETe6LPXAV9Tl2DT5U/Ra2nX0eQKUdQ5gLcBt7PjjiN8iugjaHru+590aG+OHUhymm5xfd/m2ub5FfqFlOnJPPnVee06DzeiJeiJ5DnpFF2kmm2F3cXtEu1y1yBXvxPHxivlpIAw1GsX+XD7mRvWCV9yu6sg9373v+Y/cai0ee5mPczhsgOXK1hgyk/6xpk9y6LHmWpQ0Jkb++N1wwC6VmdrajwZldGbq2h5eybG6EntIp4QAYs4+5WdAA7pv6HnBNfeOhdMfv/ORLbf0b3TxXhoyEk071/DG66PlMzmINJixUPiWUdF7vZe8Trb4tyAVoiUaabdZAQsQAlNGT8IR3sxyTDFJm8+/9+dfUjJA7bJoLZZVgDyrPIVI+UwzJYfDcK0/NekmCXnctGimDXlp4wGYGg67GQuc8SpPBYM5z6VtVtHs/EYeP9H7zdIYmWt01ywuTgZiwHK14PBgGu+ZVPEoc+PFBikqOWiY1gF9VOeHublZsEyf7enFKnkX1RbgI8JlaafY9FQYyqGON4o4VCppxik96iQllPch/c=
  - secure: IE4K/m91QHbuIHJPXcwb+7dzduxeF6c/YPM+jxDf3JKrTHckm7PMpuMk1JtTLZQfH2631bVASInaY6J4oBYJnO4m99skpKWebzFYXWBVpTBWuJrXQzO4pldiaa/U1pUcXsM1+9JZ6lmuuFf3j/MXRdanEpLty0eYEBbI1h5D1LnTiPOl37lKqe4+v5pnEWUchHzJCh30Z0JKKnRxPRujOtJ1B3vYjJ2THUN6BYLDrMG9lp8WPFmasRBN3pc7xJ/SwImfbd2YhhIogTfRoB9WqzZXLx74DLZByNbhUDWB7WPSNFp9u/ZOWMV4QyvAcbPMuv8l9cxq7EZVQ+Yxq+ioLEht01/pnH3mlyg3e/l/c54lrB9agzwUxehElh6BJw6AjEsoSZah6u1PlLa4U8XBzq5i+fS5cyJz5BIsS/3Hcu53u6D3Gdg6WiYBjQ1qRh9WcA1bRgG6FzfisuE+eDAoesiKrYkYhi+LrV+eR50Bme3os2ifaAvfYty1KfeLj2AFnJmNmASYOqzUMW0BFnh0WPj5xhU8ECQSMLJahujRn2chRmUaoDyhz9C5/8SmKnvW4Vjb2oaP0MNDoWewCQ6Qv9+3tJPLu0vKXvds369eHym2ZfXZhSZ5j2D9E9XzKFJIysCOmBlkI+IiP6k0wSkQbCKrQnECmlXSoH3o+GRxyjw=
  - secure: Pj6kNKoTWu49dGy07Xk4iY5cTEjlXGQ3HG7ecDg8g+LjLb2PMXPOHTmlecsGjW+LAuCYayAFXIXO0J0Kn91gM2Oow1Vdds/XxhJ6UMnU9MAYeZ+c/WKghv+AJy2JoNIbI3KLmxWsoomU3qfjb5VkkvVUs8HdzlsltMICdswSjczN58GZYFyAi+3i9RRwwaqgNv5PYwVLlsB2LUyq5PcoFamkET/lWX8PhRoDAJ44NZeX26NmejD2Bw45ZxaDw/8IzPDYhpSLQB6YEsoLas9z+009anTeqQ6tjCOIelh5Bmo92FH/++3mdsPGx3O9OHOYnYDVjXpZ5edwtLDTIrwnBGE41ZUFRorf5SY4Hq6U5DXtr6EsTLpIrqsB79bh4zGSQCh7PnILSjggI/HdWlBVnKyQhA/GdjEkFPORHbYRR7Zy/i+VbcBqss8MafSG2JvrxMJaiVg0pIhdIiuLdurnrlvdKiDmWhA1qle/xcfC3huh9l98c1NaU43QJC9AaBx1fmRlhrKnmtZQ34Qt2tIqWqqAkOwiBc65l/54eFMNJAaGKk0nDcr+wDRH2HRnGaeRFiEw+Jy7HF8XV7rQ1cOXP4Zp3bGMdHVaOGut9xZMUPHQCO2Xkqjea13MvS2tOm+ZRErwJ/apOLi/uSxV+kGiFWd1i9m0Q6pg4xJ3XUxDu8E=
  - secure: F7Ul9Gju0+dWPL87AvKYuJvhBeFqXhi0vTu/S9xkb3ZytVn+6M8EVjJWULY550MyKW0cuTHf9WZUathFopPGXpUyKyOz6KR414oEGD1X6lM3qLreMEOAQnVl2dSQgO1Ri4bNf2bu+c76kY5wwZPdgdnl5SBABYCzQlIiaX7Q1pm/jtsWU+M6pCYdyNdcfvkXozWNf7uYqDLQcFEzhSOxMcRkKZ30DOTFXzp5cmebzfpFvvwSikDGQWg0LQ4HdZC9HR8mzCIGIrfCygP/5lIUY2wWDfdVjL7ljby+qixBecESsj4EON/GhZmcl1IrgLKwtHLcDZSwAsPFGsLhnVd822BEipszMPsfIRLHIWraYf/2adT6td6jqkyLJGR6B7/r7XzNtn3utZh8a94bvBYuBVx2i3Q24U7nfWli/VRZvaKKN3rmPJm7nZLsbAXKDYV0wIjvXMEZoA9YYCbKhRKEsekV/VK+JHogXwrloUG9xEPUrGbVohP+X/H3AdIh+9M4m3j5PRitHia6qUb75bbbc0lQx7dBr9Dbsjx1yYNCJQqtfcevmWgWXyo7EkHTCz3hnVe0puJ8qyAAFDPzFaKBFQ6rB2TGOkvMM1ZdC4P4s4uCujO/I2wqnrbT04Z6h1S7Eh9LD4bJSRpsrBc6KPq7Y4yk8UOpZlZDy7JfnOlOPZ4=
  - secure: PSW1POO1pvCVLP+RMWzrmCd56Nx8TkVFRlUYpya4676s+cVQCg1fq+H0S5vR3yG3jSldNVq9tck4OyQEH9agm3aUeK/fa+UhUvcR1bCJN/B/eymV/jye04U38qo7UHtJ1hi6HsyWMpcQBoz+z1LihrjDT4Jx4owDCb7jpa8YGkJvW958NMxy62a8zuvt76+sxgKy5qdZxkEef2Tksabidyud9eqU46aU5r1VLuXLZ8y6X2j6j0GwIDq+jcFagefBeqTwAwPO3wAt3ZrccEHPZs8YZxyozAN2Ca+8DtUjWb9B4fu15kSkYarONZ2F0Sndlxzf/4oGkhQLsmhYCpknXGoDfJedMBRcfxgDD2v8nCI7vNPDou4I+UCL4vOrpt5FNTqDMk6KqyR0p8qP28Z8qzhD4onTX/mQmacKkgRii+IQAhLTXNKD1ufw8cc7VGJoLQlPVIUc0PfCuAbV5GIsT3rHzsn6Z9mWqem3yOcMVdKBD/rk2b7HkObas89nFF+Kw7mDdRgEd8bxwFnO3+N7S4nvHJ0m55m+FZd1bE5BAueStOmhyfD0h2npon+yNcYyOOHJw/srEuOam/crlktPVt8XSdgt3MP291ZMdtpiaRiJlIvdzCYZq5BUod4LvOD0klheAA61pKTXJXCqf8RQgrVNFYUL+R3uIouwOlFs900=
addons:
  ssh_known_hosts:
  - github.com
install:
- mvn dependency:go-offline test clean --update-snapshots --fail-never -DskipTests=true
script:
- mvn deploy site --settings=.travis/mvn-settings.xml -Ddependency.locations.enabled=false
deploy:
- provider: script
  skip_cleanup: true
  script:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${SONAR_ORGANIZATION}
    -Dsonar.login=${SONAR_TOKEN}
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
- provider: pages
  skip_cleanup: true
  github_token: "${GITHUB_TOKEN}"
  local_dir: target/site/
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
