language: java
sudo: false
branches:
  only:
  - master
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar"
env:
  global:
  - secure: VZVXK6aSbYMJunyFstkVBJypw4sJgIwy4VNPGYvVlkS00Eudo/wqarmYjlSkpDd7SgZikrkvdCRAXp3AIYmr/PLiQ64d4ORZeDNNDikrxXXFsb/Gvi7x0Mj12SymttEZaaKirhVoZnk1UxxpcjAAYCibUL/dfEl5EV7zqp/OjiwZGmrV58zH5JLJi01XNbJCB7tgjmRw9IjXLNx5a4oBO3g82vMQ2SZALYYeQ4LLnoKljGpbit6emw9RhcFywQEZyv9D0RxDHrtcSRq0vb1MFnHiyLiP+BaVZ0hoW9II0pjQT+Gwka++zb0x5hCfEtacE2KztHpwCBl79WJtCBOsZuDwh2qqqTqHUYb1ZjKpqzlS7x33VTCYpDfNhnih01Al2bBUQ3dhEXmXNLnxjKoak1hfBlgTQHQPAax+8v3sRcCVvSBQ0j/tBPvD3l9Ern2FOUrCVOVSToMdqNcdF7YqkZGxHt7fLo/63BPnK7v272PkfDzTjT/WYEMqQGrJfes1gPRF6tyI/7NpQrvlqwIlUE3kzSTEZlKnhVJOBjBHYhaXToZP13xHJi2ZYZCOvfR1KsUB7/6OPxrBaxEj1Ujr/msTFvYlHm+WPvEZptQ7ny4T0JEe9rL/TOgAEW31cl/rc37PLIreCFqdk4wjd6f9s2TJJoVpincklzRC+Bk0cdA=
  - secure: ZqI25toNAWNcePLDBbd5aLqlZR26oo9GJJZefW84VlLlDopOeWVoonBTeBxInTvok2knoMyZGNCxKpXle+A/czyv6sqK7u+yg2C1FnvoTwSMlgpeR/mNgNauY46byP8eYJhddOBm86rCchTVddLX04bzZTsws6eRvWNftJTOhYyz4hu0pv1gDBE7vbfY255SEZqbzdGL8gV/FECoLuTvcqjNlGD6HKhhyrgMBEIe4gBEUvrkL1z2uGXN/FVM8uJSqxQg/jQjDHTYRVbWoQzIzY9k86ftIgAY7JrcyLxVL+9bdjTSR/EpDyRwuQU48hxNr+RvY4IeMlkVnkMT4qBKr2S0nTv5FdcJIzIECdqS54T/I8CVdgtFuanROgfxqUx6O0gdFpF1yEdY731ixtrPPlCed4IdHLQpY3i/oi713A7rt8GxQKQR+7NwR72S7dNRHEBYgPz00FKK3GuGo9Ne6mGC2XDcqWzDDNgOXxHIsKSw27XtUzunMTzJ5+zBhvkmtbDOmcyuFTqqbcF1wgaTIiErcl2P3L2g2eFvM3eMqT0a5GgDJcpte0NC37pCOiOfeRHfYdeDN9/4LtLTxzUqKRNEtiV3mlUeqr22QZSLDiNKg4y74/zlqhJTk/cMLP1EArz+Ftrb0fi9KxUZ1HJpn49rzJBfOw7VbqgoZzALj3k=
  - secure: kWoHZC0O9zD1Zy6du6OupgxT6cNFDHxBFANl0cix38wFpvHfu8rR1M0AdcjNWQGJvav2F2GEfvdzcmUS31aoEcVnS9fYTtkO593EbEmMq/TMya6RyjbYhwOYWVs/UQuYJMkKpkI5RALWtUmn474s6Sx2PcPvkPmZYOQlN4lGR5Y8zsTGv2uXycFj1VljbAwlTn+Yg7BUFyws0KBmti9HOdlLrT0nlzAi7EN8jyo+frmC9utn0M5BFbH9DYBgoTtZ1ZWIDGPOy71yYEtG+Sf7wCwAhQESKsFZj+g+bRj8kXN9PHXrKB458Oh7aGBPDLWTwMmwnEwawAFkqK1PGgpvGQMqw1dih9JyoGYrfmqhc9TfHyOHBjYDG9EEo5BRwBcWROc5dyqwr06WOOYz/ORdSV23OxvWoTpAZ5R5XD+C3ThoOvNb0itSoT08laRvdqU5dvnodarFLjOHLNVUO4jggI+GNp+0NM25OJrgvuUrVp5iqVwWisro4V+ZvJ1oeS6PZ+yUflyrJrQrlBoacsm+JPg1bC56RU3+wqeFYJKcSSqdsj9ZyfT48OkYvmWHWYo5KTuI7LOUgPBn2S3HMsQIT6PisfrL4jZfQdcYxgnjaT+68XjY1KrsT0IBA8wdaXvxBMtWuxXTD074azOB5ydhDBm2aatswfXM6g+PHyqHZSc=
  - secure: dDAxCnsapTOVYO5dS0e0PrZFwnNWL2UNnOOLGj2wIoSUcZckjyTuhGJLle7HpvWr2uySH0sWobFhE+yPirjq+ICq/1yxbZRF3XJT3VvJoE6W+LzUEu6Bshq2iTeYAcr6Q7vxA5viGB7H0Pa7gnMyYceRydA9oNMY7aeNPRYNOiAERBnKnRM2L6DDcVd6PZ/N6wPs6nQ6LYZJXj8AcfrE7Js79cBDG/u5M9vwYjXtJfpbCZzZ0aDju9S4tHsLx70RAPROh8h0jId8h0n8T9pJMRAVipsnAXYuttQi0N2/gVdgVIJVXxitrrhAJRzRF/Ix2jQ5ogK1JPew9Ii2jrY9gRrJgccorW7t8vytyv+MVyeVBf2C1Bk80s+lz0wL7yCE8G+r/GmwvYkEy/rNv6bQC9pw/P6MppgbigyYKnN7NiPKEcb8IfBAHfjunEeub+awd8KsdjQdCUtDoaS0quw4UMmgLDDpZXT0Gjog5hMQ9aHVb4NuJcmiNi7eN30AKEsk6Skov9ZcpUyG1Mw2svG0UCcNsn1CnTUN3mq/291CMr3iHbo8lK+DnpEB0qW0wR6CvK5ezllrOxw4r9o7rVjkz6AXvztZRAddCATIoYJs9D7616vVDoB2AfQQGeehGPkRwWy+YbCmZ9n/kHk/nqa35tHLdOVBRMLx9SZmZQLzP0w=
  - secure: L8TrOKmzohaxhgaKyRZ+TVBm8kOqeMt/ydGi7XWXUXtibBwK/J5bRciRLdXMgm5G1jKj0ZwMf/YfNnmz/feC7fmukW2Jnv+baeK1HaJfMoT3kWXIsG3pfG67L2ICNHp4gIBy9puGL/r+HWVB8z05DYYwVTwxjZLgvKkEgihA89l00blnfXrusMMr1uL2JjArDMJ95MA8icySuH0THq5K4mpFBc76mhZ/fuYR9njOvdYmXn4m4fSCNgN/rUeiFBh12RNKDYvfDwc8hSe9DBOyRyqDuJWeE5CPwqrAynts0q3yCeCljkSMEwnlNTD3CBPfdS6DVH05DWrHnUendRqMWh4ZcqOYaGiHqO/a6QLYZVbI9nrWw86YDi+LBHmJc4+Pss47MtegT5C5xVEU4V4C8Vpg505664NO1iwh2JgXN57yZNzKPKXkBTPzGOSumQtYR4Xt0sIU91yDgi/XMoJhEF2a5TTdUSdcyIuv03uyggScFUzpgrdxNivZ4OZ2mOByWvkRXXe2GhtkbIblkDk5PmK7IIe6sCyYZqTC+e0Yr6JucSUDd1G1RYz67W4fnaIQFQfO7dVXFeCMjDEPpIyroRWsQh7dkdHAsLAQ7AhpXYA+paUpolhwffC+1+jiw4dCKPyD6iFsivGAbGE7sGg9pgOCuYS/BWL81x/wIDRNnMs=
addons:
  ssh_known_hosts:
  - github.com
install:
- mvn dependency:go-offline test clean --update-snapshots --fail-never -DskipTests=true
script:
- mvn deploy site --settings=.travis/mvn-settings.xml -Ddependency.locations.enabled=false
deploy:
- provider: script
  skip_cleanup: true
  script:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${SONAR_ORGANIZATION}
    -Dsonar.login=${SONAR_TOKEN}
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
- provider: pages
  skip_cleanup: true
  github_token: "${GITHUB_TOKEN}"
  local_dir: target/site/
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
