language: java
sudo: false
branches:
  only:
  - master
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar"
env:
  global:
  - secure: wx57aMdjUjBneet5oQIOEqRsXYHqOSfF1Y9LHSbbWLx5y83vkuPgD1bC1zLCNJGospuwgdc+c9x3fn4kLDbW9N6dL9PKNVN01aB3yXD8Pb+808pOMkZqV+38S0Hum9s5P9m0r62ksrWeqFqBUA1ysFk/QD8MFZK5XcsOu8WPsVL15Dt0GTsZgKM8K0FtwJBdPZEXa0a7bNgu2wOlQuFugswQI0XUOsRLLBOwCZZh3miy7IE+hbl2D8bs9Pq9vw4CXe6lkteULAT+QwUWyIPBIcrPIh1cz1v0zU0ekAJ9dR+/6ndgSG1ezdflwaWpW/BLxY93dNGptkjKxuCX1edmxV32JWZWblbDflsApNXCXfS0+iRl5YNpcAsmhA5+BKr41G8hLqC6j4uPdNTTeg57B9YVipDNpntI11+bLbqz7FTvx/4J19c84CGbOjleZc1mShZhJefmcWbK4H0U51cBJw2tI+AF4SAj+jdLHaDLHyaeWOXPbIwjLF+8GUrh8GPjr11LnfVMVWPkH2rKKcQA/PQOr4VDI4dzvhVpGguRp4w8KEanoUWfkxcNGBq5vxCGmPABLFeQRLrzRkcv1nj3pXzUBohLGGEJHzeoro849jkCeztNoIppOZgqAZGHqGYZJtt8VwPP97zZJT3yuTWnoATs+t7VxB9x4sq3ctE9yms=
  - secure: ZkCWwmW9jF1WHc7s/USmUg2a5bi0hikywzZYC1/3NZpa04TrFrvPlg5YsqTKKb3M4zLOYjffZORFCcPX7sCEHNSm/L46KOnJoKYyUBkFtV7ihGrxbSwH3U/gFtin/3KgLx512/AqecQhcjbwZg9HBNVdgsqwJSEeVtYc1D8fUxeIf3848XpGtVRzA6jGJq9Ufn8vTvVJSuzHeId/f+D1szKoHgcB9WjelLU0oY2ni5M7o7IwvK7YqWPwikHPtgYjL2j33dxgh+izQay1W7UXnycbloetEagML8RoIS2/VD2KhmehAMBiEXeA96L5/LcRfbfiNMy1mBvoi/5UTc6sx816o4nlawNsvG3TrXWcj07bU0FTqxXYpIsONncSbbXll+QySbKnzCIl+hvaQPj5vHAegb0YhY9l2hhkBQQMR77QSeEORQMLlY3ebjj0zWH/ytzsN+Q+v65EmRlw2vfDV1pg0dfzDYlYUjjGQx8cMEHmqi9CXYcmLgSNeJIrCdeMdwNOgfG4Jv2cdYUMdPPA5SjKYa8i/gUYi77BTfag/LruGy/LjAZ2tfyO1F/FSbS57yimgGqn8+saml3ck0oTWF6MaRETmIq0RqUpSl7ZdTwWX235L8pgpSbfyz5Uw6vsY4Fj45/QiMCPcyDMCTkqkZH9kpFC8uvweb8oLk7e6NA=
  - secure: a7u9XjmkJCDfTLL51eRkk+pfrkwYkQoiOjAlUtrQnpkECygNNdjccFbLOXyeJbDwatXAMKNp5CypQR9zi/mPOPWhmiUhHhrmXCYrE8TbV0qvMSuTJXWC0ZrX6UCkN3uHTNYKzfGysPtTkZyCEgUHWIQoPa3bDAzKVbhiXx2xoKlyrbshlQuKkn9H0MAEOP6TxSi88Wy49fpQI0jbD0a+9NMKmdRMoW/jcx9Oi4neJTe2BUKZRYYcJ+GL9+YjMuEI5bWkre8TPfkhfiTBh28evzhG44vRmB0ZLZwWjyF4Sw+7ZJuIJURGqrcxu0coFwPVudK4T4KIshv84DSaKORgBezMU8eoOMfjvjwVQ1605YUAhH1Gn14L9aqa7TakuLTU43JSDc/RpqPvaLySAu9p5UoZgD33vFnGateVTItHG6COqQJJ82VRaJJpfCQafX4jtUwhmamMTqSjOHAfX0U6wciYuHbHlmGZLoTKRjs0hlZObG49agEwN9UXpDPWNHX5viSeihgay0Q74x3q608ENEPkMKk+Rh8f3tEMgEDEoMkFgK2ovKmsQlvZJpkhB6ueengLyeBEuM8ObsemoPvMOM77rYlHAjNl9Z5tYDii+Op2U+UDwj9hQovgvK7M501/YHJcCeqoGxsEDzWgZWeric1zfPM213hAqsbS51250CY=
  - secure: PjtCI4H0vebUfYlSIu6RQMhdYNLBAWlpNCS7pQfdB1yT6w+Q8tQWILgd4Mfv/0Qr7UUULrhOt7KJgvCwG0bdufqesTsMERO6j020ZmfLEckK+hLdw7nB6eU/Jc6RBFUt3Y4cVy6nNk2P/8XimVZs7FQZ/VJGVtFPd8c1krKMpWCCTp/6Spi69OIi/+I7gfmGgg3nlDQosIDdCzwjSrmPjSgDmdfbZBRcQMtL2omAJRCjkt0LqVjI76OO9OSISIZj4ouNBPHQsWJ7mwhz+k3ZQGwyRGx8b9k64M5o98YYGztg7i+nG+fM8n8h6tzOIle28aW3lOa2PfHz3djcXnWeeMLp/nAw1gLVHG7WgBpg93YhneOnrjmb9C1631j50eUY8MHCx+rzAGszRYtIgfxZ7PifR6do2g/94z+CCRbUxLUelXgpvhYFdWSLkJtAt+reioggQAKXu/r7DrlbqzB6eARj+2IKAGmKxCcfRI7kTmheK38V+s/BbRpMHjDevE63zlDVkUPvoskg8xicy8gr1w2wD1Emk0ihDsrZYC9lA0j2lP2MOzFfD8gwoaIZjVoVR/ljAdR13M7y6Q/NQr+WzC8OdO48BsoW0AI/AAZlPwWdrvkN84YN74bulrEOt5E5OFYJrzFAGOtyDImsH1wrWv3sCK3JgZkkrZwE+fS9PP8=
  - secure: WFOrTr+x+0Dl0qCE1SkFNxGgqyOJzsyM/d2MkxDk/spANFrZ1JZVyJ/1m8wABiDSrbfIJRu8I8aT93uDv+6mmixlfW7vacK6akjVljknJveudsBT7DvjhwNMDw3QfyqT/tr2SjcN8ZV7RksdnU4A++1DpGitXXys51xVQRtAyTQsG16wgl91xutEzfn3hn5CAhjUTPBPXBbUW6F13TeD37k6CQPhFDmAQfNkEM8imRjZOyTsRSE7woxB3NBq8t/5uECvQncacDxPsQPKlTp9JOKYjZe7dzuVwzkNl3ZdCxfXFMGG6NHfT3YcGVhwFFn4tEYMVxsoI2ucjvJxRG+vFoYTnQIIw3NyxhmsslepHyVBWJOksJwH713HO4XxbV4QZp3W2eMPAB2H/6wX99G3lWeIrD+5zP7oZ3wSL6QnRcPiM8rTDO/TCh4zZzHBzKBXFGo1A2BfmHnbp+HjVhE3ziy0BErTZGLxvQteE7D4CKID3jhXG84hzPCUv595x1/ZXM7rjRg5MQLo2CnW1eytwTYKo2y+cOnTbstlIm0pu9nVEcEVV3oetK+TxQMKFrrubC97udJyoh7cMgnRE9XhGrTYq3ZsMTCzI+SiU+Y8Hr8e5fA6Qqz3NALvmnLJyvruKJxw+HG/RU6auXqMlK9RfxYJ0MCWceyvyOvgqBBUEvk=
addons:
  ssh_known_hosts:
  - github.com
install:
- mvn dependency:go-offline test clean --update-snapshots --fail-never -DskipTests=true
script:
- mvn deploy site --settings=.travis/mvn-settings.xml -Ddependency.locations.enabled=false
deploy:
- provider: script
  skip_cleanup: true
  script:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${SONAR_ORGANIZATION}
    -Dsonar.login=${SONAR_TOKEN}
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
- provider: pages
  skip_cleanup: true
  github_token: "${GITHUB_TOKEN}"
  local_dir: target/site/
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
