language: java
sudo: false
branches:
  only:
  - master
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar"
env:
  global:
  - secure: pNjAZSwvbymlClD66xLqCGjyoCr1VKarF56ZwfHyTQx0PzzxtgMwvOKj9yJbnTfX/brEpNxXd0WhabYbUJDiNHAVS8MxK0KJAeLy1OFibH6nqUVuVYacsIIzzSENwWDwWTY+enDBPkEPjQE+EuQ0wRlTwsF7Xb1eACsXVxK5QY9Jbg8LrX/xS2xs6SXVS6L0JDjK7z1ToNb/o8W8nPfHieyMXpRJfs2+KTo38di0yfkiLYfU5y0w6pN8O/mT09WrUusIP+yOkYeIVgDxez3fsFiGC1CLFImjGarI8yHXEoHpwFLqI4Iq7UehytCpuLNLbqOWj8Jz/W/P4dX0WiCkc8GkzIAqeRsw9IgSf0AI0jhR3oH7S0VyZy/3tRCJ2QAvTv12uLRi8ZodkEix7w51sQPJgsk0Qu7fDMZxjxNLgbL/TIWIYJINGEyWPk+beWjNDHhBIsn2K3zjrgL4D3S5tJRGgB7QNoJDrmpjCBmlfeC811gFJr3XMyZoWyjbSiW/V1HpO3L2z90C8z5HekuuBDpTO2nRNQXF+vPcvh6uJ7obx+0SfsEjgrZbC1GTtCce6VAnGYBzbmCFfBNhJk6muQoD9SdiB2AD7vuSatVnqxzCGh9zLqozH01a0zXWeS390WYSF7gI2W+dGMMQPQkkayxBIGa9HyTH0p0mZfqn0DM=
  - secure: cQgJYpNKAMEsMKq/kUO6eXHHGNNLazES7PTw/ceXVFtUYq9d7RiJHU5WVu2tD54gQ/yHe/Cd4P6DDhZqtXU5RzwkYm33ee+f12N7anDGuXuuTVFqGp5+sQZcy1yKxn7yp8D5JjbLgOGfiPzF/3F0a+JkfyR/Qx3GqIyToGNsDCSd83pxzXn9T2vVsVJduEZIjIOUMH+k63htE+TDPAQ+kjWOgPAT5zXb6y5GggjNSbuUhNTMPZzB4J3dwtGrDRl+VzhGl+q7hERwaqdUc0f1K2aHzGyKJi9OohRqDHiHRVt+XMLeHBBjYYjnOyoaTEvzKyu994lZYbQsGKLmhtYHJzC9tTWPj/IDw/uKYSf0JX3m4vkLgJqTi/S/ymoUAo+BhM4NRrLbszvyHFcu4oEQzPeHOSmJY9cEft/IbWJloLzPUur+F7JRVwux5qaY1Gmw3kUL08t69KgZATEIBqJSCJRu3dvwv8ma+XN/cPkF+siOSwSAcWJ0fAv/IH3Enxuf0rMYORDDj3oDrMQXk604BJMw7BXfkkhcTrTXK1LSvieWYXhBPmr9rWEZXtRT/v/g2N+4b1WO8zFFSs740zut9CLW3lBSa4cB4FR5FjRot4Iq/wkwQgpvX4SVO70l5NBBN1UsHp/ESyzQCe+cElhjbJULhBZbztHJv8fqS7/mXhk=
  - secure: qUdiKQAMmf9fa6x/kDSaUY75V2ihdu5M5v4EKbkvpoFTRTcwRtd02LL4yRwwm/+x40BOYHzN2n60/qcZCBD5DNUdoMdMWqSP8z4SZkjnGO5fzEKBLFvF13Sf4Mh/YNe/8leDSSIyZrdqpFtegYPlvcgqr2h+EUdii8IJHDlNRYs0iG4jpp/eBskI7rEntQ0pCnouSmyZx2b/8LHvFb20phrFLHGxfEJjYMCU9+3HnW7R0XnKnLzIQspLxOeMTYGhzfHv08Tkcm8FqiNmI4KzBgA1ddABl/27Kbr0QHkIqzGWi6yMk72uY/kCjV1Ro1u8LqFEDV+I7mbOATQPGTGBWsjRFFhFR0SejP7SXBLH8qYYoDrlwQm2KjBTdfBvjU9qezCJ7V1tModenUIs0+c0DZaikhRFexhvmI9kdohLKuBAOcfo+Ti1lHZDLaUX6sfirxptD/dgQdfsuuT9xKtqhgcwEgMQKfrOd+PSE3WSLORgUp6MXD6zbr5zh1Zrj7iQ5QB944awO+7OSraDUy0G79T92kbJbkTARr9GmXsxW5kLnXhUfDwKoNAIa20Knq03DNu2MuZzRgfwHQt6if5sGVr7o27ZSoa/+Cv3qH03/478g0Zv0erI35PaaAwtEIYrDVZJy4FUEX7v1iZk2en/NYRtLtP6gsluGV8t4wCRquI=
  - secure: D4n2KzFx6ggClnaEqF+cyqkvHkzwktzR1r7xLBtgaMaY1KrMLLaYL50EPNQSHEJJhIA43KAU7tGb4n/4jAeDUKyTCuA6f0rQvX9DTPb5UhTV3c1y1fNRo6LlUYOINw9le9BFyjiL8WyJhtCq6hpvj1zGCIVQNm61eNj0TgGefU5N/NSqKcyq3yjeAoMhaNEocKDdYBLKBDVoiZnGeTt3O94FfAuKUXIAizc4s4unpwTk8VP9HSRc7dVyb2rxK8c6P2LLuQBrLjiiygvoebQfrmgxIBQHtO5RxhSwf7I7qHA95IEDbDfsi1cBVDQ8eVgPz/n8xJZ+y6GZpWLi2mu7+3ei8F9sICCF7nXS3evnuEosEq3cCzALopx6OXxAFRxx9j9UBDlFmO3n6j/CKm1wznMoTZlpttS7ukhMk7pf/vVTltr3iuLnDs8+yfGjIqg09jT+a+ioykccxZlv0Ww2w6k9rmbzXdldM1H3Tse7G+k+72jK/3wx/vcJAlUdn8/q4eod91weyj2L3mkj2va63dUX4tqWG0KMNwW2GXg79ovksUm+hCWNxgRD7wODiCg9CwRzdsEh0/OY37wc+fFeoVYrMUb6/kRJtH/DrVXLFuzl9qgOkYhndzjmNF+vhJgF69RhPjnAOW+d4PjDQoF9l3ozVqU9f+qKJGOuBtFE1zE=
  - secure: W3nvzn9SQl4HpgQN+jxT9xTvsiRvZ+F6ZrEhR0hLzR0s75iRjhEJUq9Rpi0yfmLBNh4fcMNMcW0F4jp/D45Vqj0QErVJ5CqiKZrwWjUWyRfaljXRwaNjou2hOXD+Pd1tFEf7YBBXrrA2Gh4iCPLq4/gOEQtGRjZnzYeFQoXepAxo2Bw7mA7sVMug+XU4rLOdYvg8suVj60/jLouZO0dSgYJP6w3yF2RMpjcWs2new6IH5sJn7CNdvMkVnXw0ftwaG1U+I5DFMUSCapPuEqx4Fcp8K31tRID/fdE/JjwW5a3x7Nl1VuPdOlHNhSwyDGJhWRaUTz3uqAV4fcFRlL3LnXvQe6U1CT7radPLGXXmFaUWdOhUNjL1QjcoLkCGYnMlm2YAsjkfxWOChCi0O6FcbOGbVWRPPOp2ohM7ExgPc7hvvQNU+JGMB3+QmeBrre67H0PaUdTZvvZJupkaX8H8keLBLOfTnt7N7gT/v3Fw5AT8Mp//72q0cM+h3cHy+Q2lVj+/afBDBkwAYFSggwM086opC064M2LxsDYxSZWOd1L2iT+nlm7Hlj8wZu+fUkzplNWQgRBJXd0beKk1j/q8ZaJRIUmMUSmiRIJnIWUB7OzvyPO221EeU6FhXzjcZt1irvcIGSjH/x5GndjZDt36/3DQVMfW/czIir95F7gCDy4=
addons:
  ssh_known_hosts:
  - github.com
install:
- mvn dependency:go-offline test clean --update-snapshots --fail-never -DskipTests=true
script:
- mvn deploy site --settings=.travis/mvn-settings.xml -Ddependency.locations.enabled=false
deploy:
- provider: script
  skip_cleanup: true
  script:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${SONAR_ORGANIZATION}
    -Dsonar.login=${SONAR_TOKEN}
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
- provider: pages
  skip_cleanup: true
  github_token: "${GITHUB_TOKEN}"
  local_dir: target/site/
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
