language: java
sudo: false
branches:
  only:
  - master
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar"
env:
  global:
  - secure: vuYXLsGbM7kfPRiTWE5K75Ad/YQIulQ9vkqU3KIuC12j1wUDuyPYllRBbef6Tphz1+asQnDgmzSxpkpfbzg+EKDUas86c+2d/L29Msex45IRjYILiw3F0f42MoAK7WMUexHXlMbkk/DFndfYfYYcIKymXCrsf+LxjbO/QCHgiFA9f3TZohM7KdttqjZSjjmIyWgP5j0lN43POi9gRHYBQHX37UTPVlEx8edNr5680POCsEpL9r1j8cvHOeN7b3i95/3/JDc2rKNuVn+LEbHP+diT6KBnTRBtWgjmFZnXMm7TL1k34SVQPwX1TyqQ40AmL5ZBRgJDWSiunLJAZMH8mOJPi5PWQ9NQqLqRTB47g+I6rEHi+zpFG/WUOWg9LzZ2KhhcwWe8Q+c+qDzlhARFmuPYrt8EgaI3x8jQ53rlnucUZGx9UEwwsF1B20Xt1eAOyILCNXMPC7q2xX1N4tWyCuQV6bdSkLA35NdcWcg35zaXlM1lRHeGTrk9VR6ow6l5KW/+S20fcrTgtjmPisZ1OE6zo441pfnW15A4PRYrBkMOUXlnrcLr4xoP1koiTnFXtTwc3ZeIe3BL0l5W5dBacUoW1VX2Mi6axh0a+3B0B4sjTUqBEyl/KSE91wNvJzLEMViNMcyM940tn+gg/BScSoe/DaJRvOqzTa5OkRSYmmo=
  - secure: oOYb3Je5+gCcxEeqKcfssyOIJmlgLSI7y9qxtjy1SMcE9cOxOEA7RJHBx+nA9SA1KqA0pgDX4l5VwlcM2jaZn0RReGsBR5Esk3a0dHCl2dJL6q5eiYNQzbF5fYGj8teKKsj7LQkhsHrCrdbcEFpC5POAdbp6xOwF/h2rdtK4g/D9tnFMEJWgZojO61sLdsvWy7N/TWRBD0GHmbLwIWb6/M659o2PmOCe55qnipHgFJizWKO9fJVe6hQva17DjVuiWrSEjtUK6Fmix1zJ7OhfXNJDvXdo72z+4FUUFEh7GkfiM/Yd6cofYMSjDLXt2kPeqZAdFKaX9vqjpR8MQ+weZBZIQbsmegbNPecDu771rs6X7hQNipnI0HvBRWWXpQfvRKshVsgS/blczaDkkBB8O8Prziy0TJ06dokxVPQTdTlD+IloMsf8uTQC6K8Ky/H2ql/6P5ENinsxT+OdrV0Rzkr+Q18pwWxRLz7yt6sFbsehzpWqNgSlHqmmw/OgQyRgkSCj5eNCYSuqGUbL0HQjIyS4C7HGUwPgXBoUu7RWlUwNEBbQTHtpqh0P39JS82KtgPdotcFnGQvjk5lK9oC2alRQ2vmU3m0hFvlLVq5qKt4MnEwbvJY4tpYz1yZ3EUWrOO5iCLbEij8usY+1gVQPDpHatQp4p/vcPdaQKiM/J5g=
  - secure: ErrNJKc1GcNsIWhNNY5sIIAVc73jeph3NWb7RFXCiwMw5gzxpeaSW2EmSDLcaggHE3sXJH2hQWHduZuI9qVbYyzhhZla7ZyeGcUhaf3qOk/B8mmsKazkRq5TCt9D0CSX0lO3K2MATF5Fr+pwT2rIddhDFeRactk6Ds3aKlZdvxb2ylRw3NdyAA3D0v/knik5frrVfwzsOIBoilfW/sbAXIPPzlYE18m/ZO14tkwNsDg9VkIzquBQiTxXWLU4MnARenMcYyKmz3gb2aUrGDCXl8hPEjNwvvsXfknRZHP7ZB8FS03METYU7zSgylWg9BZ7VlX2/kS5pLzTs2uEk3CWktgypW8eEo7rqd+M4I/Ilsof6p8idzrkDT2NjCmGqWPcAzJQ70uwGfhGJU4TcaQySniBGqVEm0hnajlhr+BtTvB/yCAWps4OzgBKrlSvFxQOb0RF1ykhs3Y1nmgRE7b/HOAvTqAyeOvnOl4IRLOQ9Ixe8aIAirWsN8kpDB6L21Trz2Zzg4EzifYcX9osI1+kEpI7jnJg+yh93eLehqjkw+/Ow4HdQ/87oJdqV2/vqm9/K3X71h643ZArKNXHN4vL8TJn53qux3B2gvnDhjV4s4ZJW8kVA9eKQsMvkCTanoZ+3aTQGIY/wlog2jZrYdDK3t17uvdjwCYugPmpuNOtFjY=
  - secure: jhijlhuA3bRCiUr0XimioU3+xQSQQ6b2LFxa4yFKh8TIOwaJt3FQFBCAHNcQ+qbGBvrHH9q4bd3hUp3uyqDJbWYArjKLz0+9BT6UEAqiuMFsnm5aS+nUmanRORvHymN6SWfR2xcWfK2CBPuqIrsZ/DH7P1MQWI6m4lZRQSk+Iq8Yt9dYw8+9vYUQCh8SeXq+6s+Vlb98PXB4vdEiwuZnJpIO16u4WJUJAXiUmvCosqTDizI1s7lBiPN5A8ms8tSDtIietfJgD6oy1EPPOQprAzmxlO/lcYU9UTpx+Z9Ug0U61H/5lEioMyeD6Ybkrefc45JTPQuAvaurNt0asIyOW8mJ/OAK1IG/SXqGwRfvraVyRwtfnujJkL7CaVqZRXsVKCl1nzph3xREYK7gCj3jDwuYIEI1mMtRfDDiH24mLQBe+WBIVcIh40PvuYBH3w4Wib4ReiGLybP8eaDascdRf7ETPwGnWHfETB3HyXn1p+CfucoPi2yl613cmRv/vpGNrrk6y/s2v9KXs3JDJLDTfMF6AEqdwLVGm8jnffUOw7VlF+Egaq+Iez6I2TXC5C5djuhS+izgH02gut6JzdShv12OqH5vcHWG8sx+rdJx9Kg3kC9Mwz2OGJqvzF6Mtb0b/jJOOegmCV8ndcfypYPv8HWxeUWUiRLjU8JSAMN/hNc=
  - secure: aGZPOPwKERC/rX+6A9PuWxLEKITNAp1qT6fRf2q3+xm4PEkYPQv27pL15UFkBQaxlDfOYDHkji5ickzPpXZnxg4Lp7ic9G7GnmggBFMi7D69QVtLwmMvnBXiBgEIN2QJMVJ+tUqM7SFyoKbpKJ3/ux6z+rne+nsoSMi25a5dRQswuzqx1Jtdl0uShLP8nGx/qgb17JAE5z2UUdDnPNQKDNk3COpXfeUib9xtvUJOFxi9g+FLpFQiKHESeO1UifO3baVRQ18ua86R21pwNdGf7SWUQZS0mWWb2hrztGElsSEw8bBhQs94XJNnktiXmKxJVxCdX515JnV3ki5RkPiJWaLiiLpUeXypPQMzvo2adPKkqwOdS1WFZMrVNDVZr5gLgKx+N4EqkFkD5/+IAWVnJM/9FGqMnOvI4z6ndO9mH+dfgizdKAVX/49d2XWOcknfhOWlniE42MtiPEWBz7HUyVgylGLwEXUqoeoJL3t81/1a3Z8j0MKv8ulfapZ4y0Fub43+ToyCpIkkgFFLb3ZjQbfyJCImUVuGq65ma3ZcuhsQIjKK2m4bjsfvKZF+FKa9venNIxY6oALTA6YzW1iXLAq+UsW0uFGfJYE6p6rjJBuwlMa4VJmbDWv+f9ztDCibkpV1ltXoo7+JNzSVWrdwm8Vr0VAJ2N6Cjqk8Pd5VcyM=
addons:
  ssh_known_hosts:
  - github.com
install:
- mvn dependency:go-offline test clean --update-snapshots --fail-never -DskipTests=true
script:
- mvn deploy site --settings=.travis/mvn-settings.xml -Ddependency.locations.enabled=false
deploy:
- provider: script
  skip_cleanup: true
  script:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${SONAR_ORGANIZATION}
    -Dsonar.login=${SONAR_TOKEN}
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
- provider: pages
  skip_cleanup: true
  github_token: "${GITHUB_TOKEN}"
  local_dir: target/site/
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
