language: java
sudo: false
branches:
  only:
  - master
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar"
env:
  global:
  - secure: snqdARRgLMIEPYhgMzDZpRtM2VY9hhDw9zN0Ns/uFTYOKxA3Cr5OsW7OqRYYCHEBEd7kOkSWBpe5bEDuxDuKUYvncUr5NoxF1OwUmFJwH7JRZiMbywjuPyhx1HJ7uSQwFfGW1oXJoew/E4ORuBtd+BGv6VI/HkCQgIujUv7iAWpRdu7dSC0/DmD1DWgYH0G9KkdCof3SJiB95Q0/7dCdyoyKt1uFVBe7Mnz7F7KQ3FRjDo95J06b4dC2dpVvN1HHU3l+VLAwu+OaAA1+hjSQtAz6U0z253UIQSHU6BjLO1oAYbnhcQCiyTLIZeCAJFXZ5vGG3ixXlNb/G2BmRC62GKkX4PRUlKMgLxij5wnae0nwvWFGsOKvAUKComj4J/ESMEUuYShzhxtLDWqZlYD8Hw/IhYZG56oByUkJpJN2pFb1LJSpm5al9Ljsw9WPtinkdwtzQmMLbxWMM/Fwte3pue7WHodCeveahJOAlT87LpBq2OkhDJgM3jISMKblfbEmGULM2iYnQilpyuR8tWLdYmelTHp4Fra3OTPaBvSE1geFSFG+smWDjySo6v+gP7Z3LJvgxfZTWTv8yxGNdGprUchVA+Dj6a9YnteMO6WxUOEqUhQnqwr+Rggnz/u9JhfTQx3CMNNcU0rVPCUigFQ/lJeyfPiCMePRjlHBzK0BKEk=
  - secure: SAMSAidjkIOqq1Dh2k/ScAh8qI0bApCofXzy3CL01dtye/Fk/FcuLGAmr/033ioDvpfTrv/bUKZZtyoCBFhHgsXSN3PuFK4C2FBHz2pWr/50P+le5Y/QgsYxdo4o/ETtdiGuqepWgQ+kG9eMPhi+mt2CjHj+b5vqIBpYAxhzt5QLSxEXtGkDfCrhcx3Yb2RA8r2KU524DGGBq3HL6Y0SJS6sWkjYhXfQLMa50fcYMjMayTesvlD1qIe9rhy6NFy3Xt8lIq3ejY+LMj6XupgveFQ2Zpc5xUJzyl6I+TEKTZ4WV9wFQ4LY9GHlAxWgMffbqI7jMllc9t+cslOIwevSOHaJntYVV4GMLpe/BgSPVb3aPKqiIZp1TQt3slIdnxe7LJcfy0P3DL5X3HUaNbC4ccCdKmvVFazrx4j8cJC4eciza8lrhHvPAopb7PNq44uLmarZKLQj/kOYhJyToTiyTVskz9iJGpSx5OjJjme20gdyEiTQUDBZbbRir8Uog/fRhZRQJs4q+vN3D3ZyhFB09rhxz7hZbXxwj9+S29HzYrsyFtixKGXny9gwHXb4zgSMa+3lTaoJ1F3qsiuAIlcTS16c06AltKBqoP0rA7ShXLG8Anqg/6aWblmtkD1yNB+lGOPmKWSbRJ1+mR7P1gkqwpJsvy1PK5eiYUpxrNRqnz4=
  - secure: aGM3Jf732/IocyR3tfg+EHi0bPqxPW04hvTi9A9bYYvzI3uUhWEKE0DO+cDvSiAVSA7e5p692bl3sx311hvgZCfpBYxAmdtJP6ZT6Z1VukRp3vhYygzzw5J54ab/yLGErhuWkldyWCQRmNamDKWuoZYkFOkTQ2IndXuiNnl/niq4adM7+yIvFlswfS02us4XYgjlyKnPi3y4gpn6Op2iXEiUalPZT9ksjv7EPuzuglKOvO8eTv9JH57fil0gid9BnISfiUYO70PukmOz2g6hENCCZsD3thobkR95xUk3IYZFh9lPB4LgXroS8UoHQAFHjC5jTFfA58VK98KKoaxlWI1uDSjFsukxYCtjqrqB9bvuOF8XTHmvTdxRkF+6Sz9+Qgk1sJGnPZ89aL5CzDzMfApBhNTv1hz0ezruXqZT6UrGGUykbzK7H1G7knGKybH0xG2TmzC/ZxDX6xQCXd6I1hrV+FG1lqeWNTw3afQvLHvwG3Z/bhj1iEL9rG0xJPzxZqcb3mnhwzOuBnGHypOuzVSWlsNJuivK/GQrxBqfzH5mxv393Dn5YBSr+bfQyIk4RSVpFAkdSVxfPw607OXzWRc8Dnfd0qXDgxUBx28zJ5FeYgPOefv22iGP6rRwO4G4w1RPR5DmRdFEyAv0RJepqxWzbtvA8+DCtyabTr1V0qs=
  - secure: ECIVvHuU2LaCRx71Xy6UUpGolvpoHF6hcVn2vH/M922jiBwwpp6avgViFVuIMnRmcQszmJjUjuSXkfU8UfZa0GeLuht87edEliyi1APUB7Mc4+pMf5JWqcJAq7S+EiS3Vb2u8PM0MPKyT2rN9mupLs9smvRTUz+/bh3GB5Z7cBk/6hl8fHyVp4weBYYWc4H8IHICoPqSL9M3GYEt5C+MEuOBLgOUtaaGxVVZuV8cQGVIwwYlSIH5ga/v5OIz20rvX7u9kOs4lMfyjRBA7ZV8cH0EKcU9vlTEuNBkCfVyQtZKD6mFYfWAUgWNWrFDWPsOhD0DcFLtMlMO4lPVYQgtsKGgVwnccjvADWVJ+rr0CvlNpHYKPk63xwOM/eqkX7vJBnqztAbrmSPR9BfijWXYc5CSx5JCRAUisd1uw7nx64n/RN5IrEvZs7QcNvjOzjJv205wg1gWse1upDb0lVyjWp4+GXF9oic1+jsgQl9TPJPTcomQBxlORTxXQu5fEQqFNqaWWT4XpdxogBOZf3DJJWrvP0YiY6djtA+XvEEeB1GJnZHqoZ9ZTAoTJS532frSQ1hqXLKysBVOOzwfcWXTQiJkbWvdx1YTIwrL8JU0ReKzGXWvsuRWbRqBAZF62uMT9e9nsAcGvXsSdyg8RaduGJOzj0u/ILhDngjGC7nCUt0=
  - secure: cj6RANia4sNtCPp1sooupmBqs5suIRvpje4Z/lr8lHvGwhiBNBNdXf4uAj4YhfeMoLK5r2wPQgtvod6VbYG5q/0r2N4BXrBw297a5q/xHS4t0BGgeJfPCvBRnOvVIHtk5MRSqHWV+efyosmZTDKowkloBE0I8owkh1CKoS1zZKEIWHJ+gTf8oxGEBi+tSuqaX56CPwD6Ios4bRAh94L+CH3/zsxvcPgwOLbXV42jhpELu8IKxNiyH+npm8DfxoRslNJrN4O/We9dRMbbQY/hIngMS3kCrEfy1CuE7EiHrf7hW07EdMuWtiCnPEbCpRI7KSIG+7d/mrQFMm2v+Bx7tlVkORHTvCzLmpPVCYc3uHtJkk7A1FU/dp5r69qe8eBiu2jz7zePlKDAW/Eq4O+1sB6HkRx3SfuZjC3I8WnvbfCVQ47LUDxfBylsvmAhXS3wgczTNwldXke3JprGbyypaOJfcxrvvHkyAWLffLNlzfCved2HxO74xmX/7eANTSBD7Gh8OOMmqqIvFqTNw1TsKRSpli64gYWFICzFhexw5yhU7jyU9bHyXZSteZk4EEdg5jfMueAejFXTeVbxFmr1VLECU9r6ebyAvF2Sr5Dgn0xwzGUKUwfDFyOtwI16ZO3Ahz2mfdUVbK6XZhugvuSFAhkE1ps5xI4iOlG/YyJzsuA=
addons:
  ssh_known_hosts:
  - github.com
install:
- mvn dependency:go-offline test clean --update-snapshots --fail-never -DskipTests=true
script:
- mvn deploy site --settings=.travis/mvn-settings.xml -Ddependency.locations.enabled=false
deploy:
- provider: script
  skip_cleanup: true
  script:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${SONAR_ORGANIZATION}
    -Dsonar.login=${SONAR_TOKEN}
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
- provider: pages
  skip_cleanup: true
  github_token: "${GITHUB_TOKEN}"
  local_dir: target/site/
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
