language: java
sudo: false
branches:
  only:
  - master
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar"
env:
  global:
  - secure: AQFSFdtogIUPXcw4esArRlkj1Au17ItpO8ThG+ebQseDN3d3PI/yXtC8JsnvY8u0gNxRsoEdRrBEzFeMDPgjEvLz8RcSm0DFH8IDqCycuMPspYAsTPwugJzNokd5xONJSOvPRHAYHKLQcXBeW7yi6muDlHHqkWsfBebUmTthUaHPlOjywOLXwAeDV6zGFx7di+wcWFOzgp3qClVV40QPfl5dRF7v7TW3t9juJNKN9CenP0Hl1uBNMtZCU7ARyPLqkw8WzBcaagvcWg39F/Pz1LYvp4Zs1sbr/nK3MRBLrtJDC/KydMlEF2k8nbzj+hrfTot7J5kzi8AbLk5p5nDclua/M9n9fV6ZQ3f9HYvDKGwx4uCFwv50fhfFwaK+HNrxVWP9hu6Vmc8sdrqJ2eDCH3jRk+5ycN3Ub85RlhENlsWPHXzLm1h3Xffy3slTKNWSVflkaP/5k19yeaHFYlO0Gs54cQzWTmUqIXqkGn97GiiuKGbM7ElxIxT6fQXuN/WnOz+EFynicxBkedy7QO5EOMGCzuZQHP//oT+3uUdlXhL4Bt9h0quB45Sz0RNcxNlGcLjkrURFSracRokrA6Y++Ls8JTQLxB7uU1/f46j24ZsU/ZpgHMmABIsUjkJ58oXQn9y9/r+EnURfr30XTBjM2xn8S+0Bi7QudNzHtEGt3DQ=
  - secure: sNoWZqDS7pf5/8x8gPci2Vw2o/+CEhObsf+4WA+VQ9BIHbymnv67B3l0X/InZ1VQut+cuELR+SC53bAMK/nnsnOVH2A3e+VGpgZlvNl9YEE2+h4YRDr/I3ptOCVUYXrOzKsdXmS9xEkBiL8/Zu6EayquZeOsKx+oKHfZOi8To+2nmyQV9+ZLTJ6xGcVFxnPz2Kb0AMUw1XnDK1+f+HD4HyITSwqjxFn0swmXzPzaYTbx109cFQ1AZsmHtQPlU66le/hpx9vEEka8tfayY9J1DTOKDoKBep6Fr5eITBvXQhvvrtNVFnSsacfLzguVuObGztEYB+MUS8GF9s6E2achCjQoo9CzpDj1mBPdQFyHkyu2W1RInljmdF92INOCTJzc8q2S0ugFPTMfPTTyNezS6hdvc30y1fMLeAGA3QoT7R24VdG7ffSD8uVIVSr3MnulOAZAljeuvCV2XkUQ7tAkcpYtWg0VMfq9lktcpS4u7MClvmI9ayUDj0JoRstEM2BBIy1zxIQ83GE9Oh2ucd6bzu8jYHeF3oe6OSYNrh+Va3Q3eu4duh5P15yZP57FJRwyJ7Kte3Bg9SOuwRRrEJJ6kJLXtA+Hy3tG/Wd3OWT2dycOU7jCOCwM2pTqu+imN9wcC9vuFh/ef26csSnkxhj9MOo3M7A/BxyCMk71u9qjixI=
  - secure: eHCwB9yKoN71lniTY5Yf2gR8W0irHez9AZHT3JG/7UIitifyLi7Gk+BxZzWuztALxvS5Vb8QEfdnVjoyrjaGHKvR1N/YLTktUlaHo5RSVBA5++vr2lYCIGu+RN4PjyxaXE61j7INTHAdEFBgWwVRaHgzQXXyhCChBmgNxgzQfJ3ALqnzE7VC12/P29KpPsV4M7KORqOoIyrLYmUCrUlu34r+JG/8dgRjaOvg+dx/qRGrp6Nvmq0i9OQ3wCXq239Nj8aS9Al8kGqtGbfWEN1hQZXMqnTIpUtin9erByJjPVSYA+BLP+V1c3w3x9CB0B1QZPYB5Eqoj1SHV2YIWLx3AWMLVepTEDsvCw/YecCNU6BheLZ3jux1pgTy+HIz0+dOSbij7eCyd1CzI4HjNKUCc43d+fwZ1jh2vQ77ETrvEyUGZQyi2rug86t0TvURzTNLmwTEcU2W5wxc6yyNrQ5/7EdtyagvRD8JgSzgS12/UiqM2QCx5rr1eFbncr243GR6sNFuydzkBBH4Cn/qQM2tGTZS41sJ1Vr3WnYmmnukJ5HZAvmEk/8o/Qy14nXEA0yQMV+dpLMuOcs6VDZf/wquBqhy2182i8H3Gb8RUteNavSuF16Ey709oWuXZ9VTqs49z5feogI9nOBvsF1lGXaCGaz0a8OHib0/XL3YKf+IA8o=
  - secure: wZz752QoGHTPCFgq3IRVVLEmPcHZSrGb1B7uE80f0StSQbVocd2+r3oHqPXEojHLLlbE5t15EL1uC/4Pn8QAkk9XE3aNummbTNKUMkBL2ybuKDWQxvfCX8Apcli2GmZ/ymVoa3D6zXBUUgZgjv6scp+/k7n5mlUChzL8INoKVb5nxhbe0Ev9p+Y3JKfLh+jOtdCnZEsG2pGIO/eik1g6al/oAGF0OSVliw1AX7BdJGCX8y1NYW8MeG1rJCrlhk1sm7zXaxJihnsI9uCHjJxm+XYMycreB/4bpNf9BwddHXC2w62IwqSkBC/G9Cvxa4qhuzipvWoCjg6Koc9YdMgM0ozT/HrAmnP8OnX8L2klhbtgvWeIwdIBSs/LStzeleAjL4u2OWDktqefyNSKrrjOjUIpdnRjyXANdObEoUkzWHW3ru5RJBhRFUfyW+2OHT56lby1iRBRXOy/I38AqQbjja+zK2eYw0En3uR2jcGfDIZADMZNUsdOI/gQQHF9li0SM+PqahLopVgx+224cKWqsTopnYKfR/HeAMhiPSXA4V+aDqvpLz1UsY5elHdOqx5bHNz26ukC7f6PAR+UXXplF/4VHYmJPPDwF3I+AH/h44IY9bYZjsSz01K7I34S+7+4IfRD8mCwRQVhKQzYEqd4gtni6dmCczCFb3LrqUB02VY=
  - secure: Y0pJEz2LgD2YNY34NLffCqiDeXIGBolpqZdGgULm95S9AsCm09eZMKgb1IlbWRp5bDwyJbRcqdxRhb1SXvsplg1WU9bX968KxOqAvpggUKffx4UJj29GA5RBOWDQ6239Cs30QtTZAnswVi20w/tdoZ1J0e8nKIvEP1VeMCyVKfWUKGb05j4fm8zItEP0Cgo+SgNDD/7wecDtFGN9Q3yG+re3Uw9QcBKDY48KKb3fTsWtV7RuQb8ddiPYGaaLDoOvoytESv2DkHDeCPtZ/2FhXibmdCOrfp7yg8HBwMOzhQln0ROxSZ4tcQKBKJSkI3nb6CraQUMdD263tLwSQ9xRFqxB+HPkqAQse9uazVOsTIl/l+nirOiSRyCzydleiKHy+htUr+/JgLg4VsD7I77F5gXV5ylKOx/R6SiRpixPvctYVjqGHfWxkdPuXBa6i/frcaExK6MypAYaE++jbVV/w5hkKHKz9CYRWMRq9RrNXSxiG+nD87CtDn1SdaExVofUkGUfDdgEn8nfuG7iTKtTjbwVsu0qeiCFoKgjEetwVVWlNNpxu/4l36El88AnE4scZmD2+RU6yx3H9bGda4XYChUN5cQnzjAK5pLx9qWUq7mes968y3Lai7/TmhXt74aBen0L4K0zau9vJl/5xDOhpm5MRhpqh3sCML37Prz/obg=
addons:
  ssh_known_hosts:
  - github.com
install:
- mvn dependency:go-offline test clean --update-snapshots --fail-never -DskipTests=true
script:
- mvn deploy site --settings=.travis/mvn-settings.xml -Ddependency.locations.enabled=false
deploy:
- provider: script
  skip_cleanup: true
  script:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${SONAR_ORGANIZATION}
    -Dsonar.login=${SONAR_TOKEN}
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
- provider: pages
  skip_cleanup: true
  github_token: "${GITHUB_TOKEN}"
  local_dir: target/site/
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
